import type { ReactNode } from 'react';
import StatusBadge from '../../../../components/ui/StatusBadge.tsx';
import type {
  WorkspaceActionAccess,
  WorkspaceActionRequestHandler,
} from '../actions/workspaceActionTypes.ts';
import { WorkspaceReviewActionButtons } from './WorkspaceReviewActionButtons.tsx';
import type { ClinicalCaseDraftReviewPacketViewModel } from '../viewModels/clinicalCaseDraftReviewPacketViewModel.ts';

export function ClinicalCaseDraftReviewPacket({
  packet,
  actionAccess,
  pendingAction,
  onRunAction,
}: {
  packet: ClinicalCaseDraftReviewPacketViewModel;
  actionAccess: WorkspaceActionAccess;
  pendingAction: string | null;
  onRunAction: WorkspaceActionRequestHandler;
}) {
  const clues = packet.generatedCase.clues ?? [];
  const differentials = packet.generatedCase.differentials ?? [];

  return (
    <article className="rounded-lg border border-[var(--color-navy-border)] bg-white/[0.03] p-4">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--color-teal)]">
            Clinical Case Draft
          </p>
          <h3 className="mt-2 text-base font-semibold text-slate-100">
            {packet.title}
          </h3>
          <p className="mt-1 text-sm text-slate-400">
            {packet.intent.purpose} - {packet.intent.source}
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <StatusBadge status={packet.statusLabel} />
          <StatusBadge
            status={packet.validation.status}
            tone={packet.validation.passed ? 'success' : 'warning'}
          />
        </div>
      </div>

      <div className="mt-4 grid gap-3 lg:grid-cols-[minmax(0,1fr)_280px]">
        <section className="space-y-3">
          <PacketBlock title="Generated case">
            <p>{packet.generatedCase.summary ?? packet.generatedCase.explanation}</p>
            {clues.length ? (
              <ol className="mt-3 space-y-2">
                {clues.map((clue, index) => (
                  <li
                    key={`${packet.id}-clue-${index}`}
                    className="rounded-md border border-white/10 bg-white/[0.03] px-3 py-2"
                  >
                    <span className="text-xs font-semibold text-slate-400">
                      Clue {index + 1}
                    </span>
                    <p className="mt-1 text-slate-200">{clue}</p>
                  </li>
                ))}
              </ol>
            ) : null}
          </PacketBlock>

          {differentials.length ? (
            <PacketBlock title="Differential reasoning">
              <div className="flex flex-wrap gap-2">
                {differentials.map((differential) => (
                  <span
                    key={differential}
                    className="rounded-md border border-white/10 bg-white/[0.04] px-2.5 py-1 text-xs font-semibold text-slate-300"
                  >
                    {differential}
                  </span>
                ))}
              </div>
            </PacketBlock>
          ) : null}

          <PacketBlock title="Validation">
            <p>{packet.validation.summary}</p>
            <p className="mt-2 text-xs text-slate-500">
              {packet.validation.disclaimer}
            </p>
            {[...packet.validation.blockers, ...packet.validation.warnings].length ? (
              <ul className="mt-3 space-y-2">
                {[...packet.validation.blockers, ...packet.validation.warnings].map(
                  (finding, index) => (
                    <li key={`${packet.id}-finding-${index}`}>{finding}</li>
                  ),
                )}
              </ul>
            ) : null}
          </PacketBlock>
        </section>

        <aside className="space-y-3">
          <PacketFact label="Required decision" value={packet.intent.requiredDecision} />
          <PacketFact label="Generated by" value={packet.provenance.generationMethod} />
          <PacketFact
            label="Context hash"
            value={packet.provenance.generationContextHash ?? 'Not recorded'}
          />
          {packet.applicationHandoff.resultingCaseRevisionId ? (
            <PacketFact
              label="CaseRevision handoff"
              value={packet.applicationHandoff.resultingCaseRevisionId}
            />
          ) : null}
        </aside>
      </div>

      {packet.history.length ? (
        <div className="mt-4 border-t border-white/10 pt-3 text-xs text-slate-400">
          {packet.history.map((entry) => (
            <p key={entry.id}>
              {entry.event} - {entry.actorUserId ?? 'System'} - {entry.at}
            </p>
          ))}
        </div>
      ) : null}

      <WorkspaceReviewActionButtons
        actionIds={packet.actionIds}
        access={actionAccess}
        payload={{ draftId: packet.id }}
        pendingAction={pendingAction}
        subjectId={packet.id}
        subjectLabel={packet.title}
        includeConfirmationActions
        confirmationMessage="Apply this accepted draft into CaseRevision #1? This will create a governed Case and CaseRevision, but will not publish or schedule it."
        onRunAction={onRunAction}
      />
    </article>
  );
}

function PacketBlock({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="rounded-md border border-white/10 bg-slate-950/20 p-3 text-sm leading-6 text-slate-300">
      <h4 className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">
        {title}
      </h4>
      <div className="mt-2">{children}</div>
    </section>
  );
}

function PacketFact({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md border border-white/10 bg-white/[0.03] px-3 py-2">
      <p className="break-all text-sm font-semibold text-slate-100">{value}</p>
      <p className="mt-1 text-xs text-slate-500">{label}</p>
    </div>
  );
}
