import type {
  WorkspaceActionAccess,
  WorkspaceActionDescriptor,
  WorkspaceActionDomain,
  WorkspaceActionId,
  WorkspaceActionIntent,
} from './workspaceActionTypes.ts';

export const WORKSPACE_ACTION_REGISTRY: Record<
  WorkspaceActionId,
  WorkspaceActionDescriptor
> = {
  'teachingRule.approve': descriptor({
    id: 'teachingRule.approve',
    domain: 'teachingRule',
    intent: 'approve',
    label: 'Approve teaching rule',
    description: 'Approve a teaching rule candidate for this diagnosis.',
    requiredAccess: 'seniorEditorial',
    successMessage: 'Teaching rule approved.',
    failureMessage: 'Unable to approve teaching rule.',
    sourceWorkflows: ['teaching', 'reviewQueue'],
  }),
  'teachingRule.reject': descriptor({
    id: 'teachingRule.reject',
    domain: 'teachingRule',
    intent: 'reject',
    label: 'Reject teaching rule',
    description: 'Reject a teaching rule candidate.',
    requiredAccess: 'seniorEditorial',
    successMessage: 'Teaching rule rejected.',
    failureMessage: 'Unable to reject teaching rule.',
    sourceWorkflows: ['teaching', 'reviewQueue'],
  }),
  'teachingRule.requestChanges': descriptor({
    id: 'teachingRule.requestChanges',
    domain: 'teachingRule',
    intent: 'requestChanges',
    label: 'Request teaching rule changes',
    description: 'Send a teaching rule back for changes.',
    requiredAccess: 'editorial',
    successMessage: 'Teaching rule changes requested.',
    failureMessage: 'Unable to request teaching rule changes.',
    sourceWorkflows: ['teaching', 'reviewQueue'],
  }),
  'teachingRule.generateCandidates': descriptor({
    id: 'teachingRule.generateCandidates',
    domain: 'teachingRule',
    intent: 'generate',
    label: 'Generate teaching rule candidates',
    description: 'Generate teaching rule candidates using the existing backend helper.',
    requiredAccess: 'editorial',
    successMessage: 'Teaching rule candidates generated.',
    failureMessage: 'Unable to generate teaching rule candidates.',
    sourceWorkflows: ['teaching'],
  }),
  'teachingRule.seedLegacy': descriptor({
    id: 'teachingRule.seedLegacy',
    domain: 'teachingRule',
    intent: 'generate',
    label: 'Seed legacy teaching rules',
    description: 'Seed teaching rules from legacy content.',
    requiredAccess: 'seniorEditorial',
    confirmationRequired: true,
    successMessage: 'Legacy teaching rules seeded.',
    failureMessage: 'Unable to seed legacy teaching rules.',
    sourceWorkflows: ['teaching'],
  }),
  'evidence.approveRelationship': descriptor({
    id: 'evidence.approveRelationship',
    domain: 'evidence',
    intent: 'approve',
    label: 'Approve evidence relationship',
    description: 'Approve an evidence graph relationship.',
    requiredAccess: 'seniorEditorial',
    successMessage: 'Evidence relationship approved.',
    failureMessage: 'Unable to approve evidence relationship.',
    sourceWorkflows: ['reasoning', 'reviewQueue'],
  }),
  'evidence.rejectRelationship': descriptor({
    id: 'evidence.rejectRelationship',
    domain: 'evidence',
    intent: 'reject',
    label: 'Reject evidence relationship',
    description: 'Reject an evidence graph relationship.',
    requiredAccess: 'seniorEditorial',
    successMessage: 'Evidence relationship rejected.',
    failureMessage: 'Unable to reject evidence relationship.',
    sourceWorkflows: ['reasoning', 'reviewQueue'],
  }),
  'evidence.generateCandidates': descriptor({
    id: 'evidence.generateCandidates',
    domain: 'evidence',
    intent: 'generate',
    label: 'Generate evidence candidates',
    description: 'Generate evidence graph candidates for review.',
    requiredAccess: 'editorial',
    successMessage: 'Evidence candidates generated.',
    failureMessage: 'Unable to generate evidence candidates.',
    sourceWorkflows: ['reasoning'],
  }),
  'reasoningPath.approve': descriptor({
    id: 'reasoningPath.approve',
    domain: 'reasoningPath',
    intent: 'approve',
    label: 'Approve reasoning path',
    description: 'Approve a reasoning path.',
    requiredAccess: 'seniorEditorial',
    successMessage: 'Reasoning path approved.',
    failureMessage: 'Unable to approve reasoning path.',
    sourceWorkflows: ['reasoning', 'reviewQueue'],
  }),
  'reasoningPath.reject': descriptor({
    id: 'reasoningPath.reject',
    domain: 'reasoningPath',
    intent: 'reject',
    label: 'Reject reasoning path',
    description: 'Reject a reasoning path.',
    requiredAccess: 'seniorEditorial',
    successMessage: 'Reasoning path rejected.',
    failureMessage: 'Unable to reject reasoning path.',
    sourceWorkflows: ['reasoning', 'reviewQueue'],
  }),
  'reasoningPath.requestChanges': descriptor({
    id: 'reasoningPath.requestChanges',
    domain: 'reasoningPath',
    intent: 'requestChanges',
    label: 'Request reasoning path changes',
    description: 'Send a reasoning path back for changes.',
    requiredAccess: 'editorial',
    successMessage: 'Reasoning path changes requested.',
    failureMessage: 'Unable to request reasoning path changes.',
    sourceWorkflows: ['reasoning', 'reviewQueue'],
  }),
  'reasoningPath.generateCandidates': descriptor({
    id: 'reasoningPath.generateCandidates',
    domain: 'reasoningPath',
    intent: 'generate',
    label: 'Generate reasoning path candidates',
    description: 'Generate reasoning path candidates for this diagnosis.',
    requiredAccess: 'editorial',
    successMessage: 'Reasoning path candidates generated.',
    failureMessage: 'Unable to generate reasoning path candidates.',
    sourceWorkflows: ['reasoning'],
  }),
  'reasoningPath.validateDraft': descriptor({
    id: 'reasoningPath.validateDraft',
    domain: 'reasoningPath',
    intent: 'review',
    label: 'Validate reasoning draft',
    description: 'Run reasoning draft validation.',
    requiredAccess: 'editorial',
    successMessage: 'Reasoning draft validation started.',
    failureMessage: 'Unable to validate reasoning draft.',
    sourceWorkflows: ['reasoning', 'publish'],
  }),
  'clueRevision.approve': descriptor({
    id: 'clueRevision.approve',
    domain: 'clueRevision',
    intent: 'approve',
    label: 'Approve clue revision',
    description: 'Approve a clue revision draft.',
    requiredAccess: 'seniorEditorial',
    successMessage: 'Clue revision approved.',
    failureMessage: 'Unable to approve clue revision.',
    sourceWorkflows: ['cases', 'reviewQueue'],
  }),
  'clueRevision.reject': descriptor({
    id: 'clueRevision.reject',
    domain: 'clueRevision',
    intent: 'reject',
    label: 'Reject clue revision',
    description: 'Reject a clue revision draft.',
    requiredAccess: 'seniorEditorial',
    successMessage: 'Clue revision rejected.',
    failureMessage: 'Unable to reject clue revision.',
    sourceWorkflows: ['cases', 'reviewQueue'],
  }),
  'clueRevision.requestChanges': descriptor({
    id: 'clueRevision.requestChanges',
    domain: 'clueRevision',
    intent: 'requestChanges',
    label: 'Request clue revision changes',
    description: 'Request changes to a clue revision draft.',
    requiredAccess: 'editorial',
    successMessage: 'Clue revision changes requested.',
    failureMessage: 'Unable to request clue revision changes.',
    sourceWorkflows: ['cases', 'reviewQueue'],
  }),
  'clueRevision.supersede': descriptor({
    id: 'clueRevision.supersede',
    domain: 'clueRevision',
    intent: 'supersede',
    label: 'Supersede clue revision',
    description: 'Supersede a clue revision draft.',
    requiredAccess: 'seniorEditorial',
    successMessage: 'Clue revision superseded.',
    failureMessage: 'Unable to supersede clue revision.',
    sourceWorkflows: ['cases', 'reviewQueue'],
  }),
  'clueRevision.apply': descriptor({
    id: 'clueRevision.apply',
    domain: 'clueRevision',
    intent: 'apply',
    label: 'Apply clue revision',
    description: 'Apply an approved clue revision draft.',
    requiredAccess: 'seniorEditorial',
    confirmationRequired: true,
    successMessage: 'Clue revision applied.',
    failureMessage: 'Unable to apply clue revision.',
    sourceWorkflows: ['cases', 'publish'],
  }),
  'clueRevision.update': descriptor({
    id: 'clueRevision.update',
    domain: 'clueRevision',
    intent: 'update',
    label: 'Update clue revision',
    description: 'Update a clue revision draft.',
    requiredAccess: 'editorial',
    successMessage: 'Clue revision updated.',
    failureMessage: 'Unable to update clue revision.',
    sourceWorkflows: ['cases'],
  }),
  'education.repairUnsupportedClaim': descriptor({
    id: 'education.repairUnsupportedClaim',
    domain: 'claimRepair',
    intent: 'repair',
    label: 'Repair unsupported claim',
    description: 'Generate a repair draft for an unsupported education claim.',
    requiredAccess: 'editorial',
    successMessage: 'Claim repair draft generated.',
    failureMessage: 'Unable to generate claim repair draft.',
    sourceWorkflows: ['content', 'publish', 'reviewQueue'],
  }),
  'education.regenerateSection': descriptor({
    id: 'education.regenerateSection',
    domain: 'education',
    intent: 'generate',
    label: 'Regenerate education section',
    description: 'Regenerate a learner-facing education section.',
    requiredAccess: 'editorial',
    confirmationRequired: true,
    successMessage: 'Education section regeneration started.',
    failureMessage: 'Unable to regenerate education section.',
    sourceWorkflows: ['content'],
  }),
  'education.review': descriptor({
    id: 'education.review',
    domain: 'education',
    intent: 'review',
    label: 'Review education',
    description: 'Submit an education review decision.',
    requiredAccess: 'seniorEditorial',
    confirmationRequired: true,
    successMessage: 'Education review submitted.',
    failureMessage: 'Unable to submit education review.',
    sourceWorkflows: ['content', 'publish'],
  }),
  'publication.normalizeLifecycle': descriptor({
    id: 'publication.normalizeLifecycle',
    domain: 'lifecycle',
    intent: 'normalize',
    label: 'Normalize lifecycle',
    description: 'Normalize diagnosis lifecycle projection.',
    requiredAccess: 'seniorEditorial',
    confirmationRequired: true,
    successMessage: 'Lifecycle normalized.',
    failureMessage: 'Unable to normalize lifecycle.',
    sourceWorkflows: ['publish'],
  }),
  'publication.performLifecycleAction': descriptor({
    id: 'publication.performLifecycleAction',
    domain: 'publication',
    intent: 'review',
    label: 'Perform lifecycle action',
    description: 'Perform a lifecycle governance action.',
    requiredAccess: 'seniorEditorial',
    confirmationRequired: true,
    successMessage: 'Lifecycle action completed.',
    failureMessage: 'Unable to complete lifecycle action.',
    sourceWorkflows: ['publish'],
  }),
  'publication.markCaseReady': descriptor({
    id: 'publication.markCaseReady',
    domain: 'publication',
    intent: 'markReady',
    label: 'Mark case ready',
    description: 'Mark a case ready to publish.',
    requiredAccess: 'seniorEditorial',
    confirmationRequired: true,
    successMessage: 'Case marked ready to publish.',
    failureMessage: 'Unable to mark case ready.',
    sourceWorkflows: ['cases', 'publish'],
  }),
  'publication.authorizeRevision': descriptor({
    id: 'publication.authorizeRevision',
    domain: 'publication',
    intent: 'authorize',
    label: 'Authorize exact revision publication',
    description: 'Authorize publication for the current approved CaseRevision.',
    requiredAccess: 'seniorEditorial',
    confirmationRequired: true,
    successMessage: 'CaseRevision publication authorized.',
    failureMessage: 'Unable to authorize CaseRevision publication.',
    sourceWorkflows: ['cases', 'publish', 'reviewQueue'],
  }),
  'caseRevision.startReview': descriptor({
    id: 'caseRevision.startReview',
    domain: 'caseRevision',
    intent: 'review',
    label: 'Start CaseRevision review',
    description: 'Open an exact review context for the current CaseRevision.',
    requiredAccess: 'editorial',
    successMessage: 'CaseRevision review started.',
    failureMessage: 'Unable to start CaseRevision review.',
    sourceWorkflows: ['cases', 'reviewQueue'],
  }),
  'caseRevision.approve': descriptor({
    id: 'caseRevision.approve',
    domain: 'caseRevision',
    intent: 'approve',
    label: 'Approve exact CaseRevision',
    description: 'Submit governed APP-006 approval for the active CaseRevision review.',
    requiredAccess: 'seniorEditorial',
    confirmationRequired: true,
    successMessage: 'CaseRevision approved.',
    failureMessage: 'Unable to approve CaseRevision.',
    sourceWorkflows: ['cases', 'reviewQueue'],
  }),
  'caseCoverage.create': descriptor({
    id: 'caseCoverage.create',
    domain: 'caseCoverage',
    intent: 'create',
    label: 'Create case coverage',
    description: 'Create a case learning-goal coverage row.',
    requiredAccess: 'editorial',
    successMessage: 'Case coverage created.',
    failureMessage: 'Unable to create case coverage.',
    sourceWorkflows: ['cases', 'teaching'],
  }),
  'caseCoverage.update': descriptor({
    id: 'caseCoverage.update',
    domain: 'caseCoverage',
    intent: 'update',
    label: 'Update case coverage',
    description: 'Update a case learning-goal coverage row.',
    requiredAccess: 'editorial',
    successMessage: 'Case coverage updated.',
    failureMessage: 'Unable to update case coverage.',
    sourceWorkflows: ['cases', 'teaching'],
  }),
  'caseCoverage.delete': descriptor({
    id: 'caseCoverage.delete',
    domain: 'caseCoverage',
    intent: 'delete',
    label: 'Delete case coverage',
    description: 'Delete a case learning-goal coverage row.',
    requiredAccess: 'seniorEditorial',
    destructive: true,
    confirmationRequired: true,
    successMessage: 'Case coverage deleted.',
    failureMessage: 'Unable to delete case coverage.',
    sourceWorkflows: ['cases', 'teaching'],
  }),
  'caseAnnotation.create': descriptor({
    id: 'caseAnnotation.create',
    domain: 'caseAnnotation',
    intent: 'create',
    label: 'Create case annotation',
    description: 'Create a case escalation or discriminator annotation.',
    requiredAccess: 'editorial',
    successMessage: 'Case annotation created.',
    failureMessage: 'Unable to create case annotation.',
    sourceWorkflows: ['cases', 'reasoning'],
  }),
  'caseAnnotation.update': descriptor({
    id: 'caseAnnotation.update',
    domain: 'caseAnnotation',
    intent: 'update',
    label: 'Update case annotation',
    description: 'Update a case escalation or discriminator annotation.',
    requiredAccess: 'editorial',
    successMessage: 'Case annotation updated.',
    failureMessage: 'Unable to update case annotation.',
    sourceWorkflows: ['cases', 'reasoning'],
  }),
  'caseAnnotation.delete': descriptor({
    id: 'caseAnnotation.delete',
    domain: 'caseAnnotation',
    intent: 'delete',
    label: 'Delete case annotation',
    description: 'Delete a case escalation or discriminator annotation.',
    requiredAccess: 'seniorEditorial',
    destructive: true,
    confirmationRequired: true,
    successMessage: 'Case annotation deleted.',
    failureMessage: 'Unable to delete case annotation.',
    sourceWorkflows: ['cases', 'reasoning'],
  }),
  'caseDraft.accept': descriptor({
    id: 'caseDraft.accept',
    domain: 'caseDraft',
    intent: 'approve',
    label: 'Accept clinical case draft',
    description: 'Accept a generated Clinical Case Draft without applying it.',
    requiredAccess: 'editorial',
    successMessage: 'Clinical Case Draft accepted.',
    failureMessage: 'Unable to accept Clinical Case Draft.',
    sourceWorkflows: ['cases', 'reviewQueue'],
  }),
  'caseDraft.reject': descriptor({
    id: 'caseDraft.reject',
    domain: 'caseDraft',
    intent: 'reject',
    label: 'Reject clinical case draft',
    description: 'Reject a generated Clinical Case Draft.',
    requiredAccess: 'editorial',
    successMessage: 'Clinical Case Draft rejected.',
    failureMessage: 'Unable to reject Clinical Case Draft.',
    sourceWorkflows: ['cases', 'reviewQueue'],
  }),
  'caseDraft.requestChanges': descriptor({
    id: 'caseDraft.requestChanges',
    domain: 'caseDraft',
    intent: 'requestChanges',
    label: 'Request clinical case draft changes',
    description: 'Return a generated Clinical Case Draft for changes.',
    requiredAccess: 'editorial',
    successMessage: 'Clinical Case Draft changes requested.',
    failureMessage: 'Unable to request Clinical Case Draft changes.',
    sourceWorkflows: ['cases', 'reviewQueue'],
  }),
  'caseDraft.apply': descriptor({
    id: 'caseDraft.apply',
    domain: 'caseDraft',
    intent: 'apply',
    label: 'Apply accepted Clinical Case Draft',
    description: 'Apply an accepted draft into an initial CaseRevision.',
    requiredAccess: 'editorial',
    confirmationRequired: true,
    successMessage: 'Accepted Clinical Case Draft applied.',
    failureMessage: 'Unable to apply accepted Clinical Case Draft.',
    sourceWorkflows: ['cases', 'reviewQueue'],
  }),
};

export const WORKSPACE_ACTION_DOMAINS: WorkspaceActionDomain[] = [
  'teachingRule',
  'evidence',
  'reasoningPath',
  'clueRevision',
  'education',
  'publication',
  'claimRepair',
  'lifecycle',
  'caseCoverage',
  'caseAnnotation',
  'caseRevision',
  'caseDraft',
];

export const WORKSPACE_ACTION_INTENTS: WorkspaceActionIntent[] = [
  'approve',
  'reject',
  'requestChanges',
  'supersede',
  'apply',
  'generate',
  'repair',
  'normalize',
  'markReady',
  'authorize',
  'review',
  'create',
  'update',
  'delete',
];

export function getWorkspaceActionDescriptor(
  actionId: WorkspaceActionId,
): WorkspaceActionDescriptor {
  return WORKSPACE_ACTION_REGISTRY[actionId];
}

export function isWorkspaceActionId(
  actionId: string,
): actionId is WorkspaceActionId {
  return actionId in WORKSPACE_ACTION_REGISTRY;
}

export function canRunWorkspaceAction(
  actionId: WorkspaceActionId,
  access: WorkspaceActionAccess,
): boolean {
  const action = getWorkspaceActionDescriptor(actionId);
  if (!access.canAccessEditorial) return false;
  if (action.requiredAccess === 'seniorEditorial') {
    return access.canPublishEditorial;
  }
  return true;
}

export function requiresConfirmation(actionId: WorkspaceActionId): boolean {
  const action = getWorkspaceActionDescriptor(actionId);
  return Boolean(action.confirmationRequired || action.destructive);
}

function descriptor(
  descriptorValue: WorkspaceActionDescriptor,
): WorkspaceActionDescriptor {
  return descriptorValue;
}
