export const COMMAND_CONTRACT_STATUSES = [
  'DRAFT',
  'APPROVED',
  'DEPRECATED',
  'WITHDRAWN',
] as const;
export const PRECONDITION_MODES = [
  'EXACT_REVISION',
  'EXPECTED_VERSION',
  'EXPECTED_TOKEN',
] as const;
export const IDEMPOTENCY_POLICIES = [
  'REQUIRED',
  'OPTIONAL',
  'PROHIBITED',
] as const;
export const BATCH_POLICIES = [
  'ATOMIC',
  'INDEPENDENT_ITEMS',
  'PROHIBITED',
] as const;
export const CURRENT_STATE_STATUSES = [
  'KNOWN',
  'UNKNOWN',
  'UNAVAILABLE',
] as const;
export const PRIOR_RESULT_STATUSES = [
  'SUCCESS',
  'REJECTED_STALE',
  'REJECTED_INVALID',
  'REJECTED_AUTHORITY',
  'FAILED_NO_EFFECT',
] as const;
export const GOVERNED_COMMAND_RESOLUTION_STATUSES = [
  'ELIGIBLE',
  'REJECTED_MISSING_CONTRACT',
  'REJECTED_UNAPPROVED_CONTRACT',
  'REJECTED_MISSING_PRECONDITION',
  'REJECTED_STALE_PRECONDITION',
  'REJECTED_CURRENT_STATE_UNKNOWN',
  'REJECTED_CONFLICTING_PRECONDITIONS',
  'REJECTED_IDEMPOTENCY_CONFLICT',
  'REJECTED_AUTHORITY',
  'REPLAY_OF_SUCCESSFUL_COMMAND',
  'REPLAY_OF_REJECTED_COMMAND',
  'INVALID',
] as const;
export const APPROVED_OPTION_ID =
  'OPTION_D_HYBRID_EXPECTED_REVISION_VERSION_AND_TOKEN_CONTRACT';
