export const APPROVED_OPTION_ID =
  'OPTION_D_TRANSITIONAL_HYBRID_CANONICAL_OWNER_AND_CONTROLLED_PROJECTIONS';

export const PROJECTION_DEFINITION_STATUSES = [
  'DRAFT',
  'APPROVED',
  'DEPRECATED',
  'WITHDRAWN',
] as const;

export const OWNERSHIP_STATUSES = [
  'APPROVED_CANONICAL_OWNER',
  'UNRESOLVED_OWNER',
  'DEPRECATED_NO_OWNER_REQUIRED',
] as const;

export const SYNCHRONIZATION_STRATEGIES = [
  'DERIVED_ON_READ',
  'ATOMIC_SYNCHRONOUS',
  'ASYNCHRONOUS_BOUNDED_DRIFT',
  'LEGACY_OBSERVED_ONLY',
  'DEPRECATED',
] as const;

export const WRITER_POLICIES = [
  'GOVERNED_HANDLER_ONLY',
  'DERIVATION_ONLY',
  'TEMPORARY_COMPATIBILITY_WRITE',
  'OBSERVE_ONLY',
  'NO_WRITES',
] as const;

export const PROJECTION_SENSITIVITIES = [
  'AUTHORITY_SENSITIVE',
  'LEARNER_EXPOSURE_GATING',
  'OPERATIONAL_ELIGIBILITY',
  'NON_AUTHORITY_COMPATIBILITY',
  'UNKNOWN',
] as const;

export const INVENTORY_COMPLETENESS = [
  'COMPLETE',
  'PARTIAL',
  'UNKNOWN',
] as const;

export const SNAPSHOT_KINDS = ['CANONICAL', 'PROJECTED'] as const;
export const STATE_STATUSES = [
  'KNOWN',
  'UNKNOWN',
  'UNAVAILABLE',
  'MISSING',
] as const;

export const DRIFT_STATUSES = [
  'IN_SYNC',
  'DRIFTED',
  'OWNER_UNRESOLVED',
  'CANONICAL_STATE_UNKNOWN',
  'PROJECTION_STATE_UNKNOWN',
  'NOT_EVALUABLE',
  'PROJECTION_MISSING',
  'CANONICAL_EFFECT_MISSING',
] as const;

export const REPAIR_MODES = [
  'REBUILD_FROM_CANONICAL',
  'REPLAY_PROVEN_CANONICAL_EFFECT',
  'MARK_UNKNOWN',
  'MANUAL_GOVERNED_REVIEW_REQUIRED',
  'NO_AUTOMATIC_REPAIR',
] as const;

export const LEGACY_PROVENANCE_STATUSES = [
  'OBSERVED_ONLY',
  'SOURCE_VERIFIED',
  'CANONICAL_LINK_UNKNOWN',
  'CONFLICTING',
  'UNKNOWN',
] as const;
