import {
  WEOS_ALIGNMENT_CLASSIFICATIONS,
  type WeosAlignmentClassification,
} from './canonical-concepts';

export const WEOS_ARTIFACT_TYPES = {
  DIAGNOSIS_REGISTRY: 'DIAGNOSIS_REGISTRY',
  DIAGNOSIS_ALIAS: 'DIAGNOSIS_ALIAS',
  DIAGNOSIS_REGISTRY_CANDIDATE: 'DIAGNOSIS_REGISTRY_CANDIDATE',
  REGISTRY_ACTIVATION_STATE: 'REGISTRY_ACTIVATION_STATE',
  DIAGNOSIS_OPERATIONAL_PERMISSION: 'DIAGNOSIS_OPERATIONAL_PERMISSION',
  DIAGNOSIS_ONBOARDING_PROGRESS: 'DIAGNOSIS_ONBOARDING_PROGRESS',
  DIAGNOSIS_OPERATION_READINESS: 'DIAGNOSIS_OPERATION_READINESS',
  EDITORIAL_BRIEF: 'EDITORIAL_BRIEF',
  LEARNING_GOAL: 'LEARNING_GOAL',
  TEACHING_RULE: 'TEACHING_RULE',
  REASONING_PATH: 'REASONING_PATH',
  REASONING_VALIDATION_RESULT: 'REASONING_VALIDATION_RESULT',
  CLINICAL_CASE: 'CLINICAL_CASE',
  CASE_REVISION: 'CASE_REVISION',
  CASE_EXPLANATION: 'CASE_EXPLANATION',
  CLINICAL_CLUE: 'CLINICAL_CLUE',
  CLUE_PROGRESSION_ANALYSIS: 'CLUE_PROGRESSION_ANALYSIS',
  CLUE_DISCRIMINATOR_ANNOTATION: 'CLUE_DISCRIMINATOR_ANNOTATION',
  ESCALATION_ANNOTATION: 'ESCALATION_ANNOTATION',
  DIAGNOSIS_EDUCATION: 'DIAGNOSIS_EDUCATION',
  DIAGNOSIS_EDUCATION_REVISION: 'DIAGNOSIS_EDUCATION_REVISION',
  GRAPH_CANDIDATE: 'GRAPH_CANDIDATE',
  GRAPH_FACT: 'GRAPH_FACT',
  TEACHING_RELATIONSHIP: 'TEACHING_RELATIONSHIP',
  EVIDENCE_NODE: 'EVIDENCE_NODE',
  EVIDENCE_RELATIONSHIP: 'EVIDENCE_RELATIONSHIP',
  EVIDENCE_SOURCE: 'EVIDENCE_SOURCE',
  CLAIM_SUPPORT_LINK: 'CLAIM_SUPPORT_LINK',
  REFERENCE_LIST: 'REFERENCE_LIST',
  EVIDENCE_ASSESSMENT: 'EVIDENCE_ASSESSMENT',
  DIFFERENTIAL_MAPPING: 'DIFFERENTIAL_MAPPING',
  DIFFERENTIAL_LINK: 'DIFFERENTIAL_LINK',
  AI_DRAFT: 'AI_DRAFT',
  AI_DRAFT_ACCEPTANCE: 'AI_DRAFT_ACCEPTANCE',
  CLUE_REVISION_DRAFT: 'CLUE_REVISION_DRAFT',
  VALIDATION_RESULT: 'VALIDATION_RESULT',
  EDITORIAL_ASSESSMENT: 'EDITORIAL_ASSESSMENT',
  CLINICAL_ASSESSMENT: 'CLINICAL_ASSESSMENT',
  EDUCATIONAL_ASSESSMENT: 'EDUCATIONAL_ASSESSMENT',
  REASONING_ASSESSMENT: 'REASONING_ASSESSMENT',
  SAFETY_ASSESSMENT: 'SAFETY_ASSESSMENT',
  LEARNING_GOAL_COVERAGE_ASSESSMENT: 'LEARNING_GOAL_COVERAGE_ASSESSMENT',
  EDITORIAL_REVIEW: 'EDITORIAL_REVIEW',
  REVIEW_PACKET_SNAPSHOT: 'REVIEW_PACKET_SNAPSHOT',
  EDITORIAL_DECISION: 'EDITORIAL_DECISION',
  READINESS_ASSESSMENT: 'READINESS_ASSESSMENT',
  PUBLICATION_READINESS_ASSESSMENT: 'PUBLICATION_READINESS_ASSESSMENT',
  PUBLICATION_ASSESSMENT: 'PUBLICATION_ASSESSMENT',
  PUBLICATION_DECISION: 'PUBLICATION_DECISION',
  PUBLISHED_ARTIFACT_VERSION: 'PUBLISHED_ARTIFACT_VERSION',
  PUBLICATION_SCHEDULE: 'PUBLICATION_SCHEDULE',
  RELEASE_EVENT: 'RELEASE_EVENT',
  LEARNER_EXPOSURE_REFERENCE: 'LEARNER_EXPOSURE_REFERENCE',
  WITHDRAWAL_RECORD: 'WITHDRAWAL_RECORD',
  SUPERSESSION_RECORD: 'SUPERSESSION_RECORD',
  PUBLICATION_HISTORY: 'PUBLICATION_HISTORY',
  CONTROLLED_APPLICATION_RECORD: 'CONTROLLED_APPLICATION_RECORD',
  MATERIAL_CHANGE_DETERMINATION: 'MATERIAL_CHANGE_DETERMINATION',
  GOVERNANCE_RECORD: 'GOVERNANCE_RECORD',
  AUDIT_EVENT: 'AUDIT_EVENT',
  AUTHORITY_ASSIGNMENT: 'AUTHORITY_ASSIGNMENT',
  AUTHORITY_SCOPE: 'AUTHORITY_SCOPE',
  REVIEWER_ASSIGNMENT: 'REVIEWER_ASSIGNMENT',
  CONFLICT_OF_INTEREST_DECLARATION: 'CONFLICT_OF_INTEREST_DECLARATION',
  DISAGREEMENT_RECORD: 'DISAGREEMENT_RECORD',
  ADJUDICATION_RECORD: 'ADJUDICATION_RECORD',
  GOVERNANCE_EXCEPTION: 'GOVERNANCE_EXCEPTION',
  EMERGENCY_CORRECTION: 'EMERGENCY_CORRECTION',
  PUBLICATION_AUTHORITY: 'PUBLICATION_AUTHORITY',
  ARTIFACT_OWNERSHIP: 'ARTIFACT_OWNERSHIP',
  MAINTENANCE_OWNERSHIP: 'MAINTENANCE_OWNERSHIP',
  MAINTENANCE_ASSESSMENT: 'MAINTENANCE_ASSESSMENT',
  EVIDENCE_REFRESH_TRIGGER: 'EVIDENCE_REFRESH_TRIGGER',
  GUIDELINE_CHANGE_TRIGGER: 'GUIDELINE_CHANGE_TRIGGER',
  REVIEW_DUE_DATE: 'REVIEW_DUE_DATE',
  REVALIDATION_OBLIGATION: 'REVALIDATION_OBLIGATION',
  CORRECTION_WORKFLOW: 'CORRECTION_WORKFLOW',
  RETIREMENT_ASSESSMENT: 'RETIREMENT_ASSESSMENT',
  WITHDRAWAL_READINESS: 'WITHDRAWAL_READINESS',
  SUPERSESSION_REVIEW: 'SUPERSESSION_REVIEW',
} as const;

export type WeosArtifactType =
  (typeof WEOS_ARTIFACT_TYPES)[keyof typeof WEOS_ARTIFACT_TYPES];

export type CandidateGovernedClassification =
  | 'CANDIDATE_KNOWLEDGE'
  | 'GOVERNED_KNOWLEDGE'
  | 'GOVERNANCE_RECORD'
  | 'ASSESSMENT_RECORD'
  | 'DECISION_RECORD'
  | 'OPERATIONAL_RECORD'
  | 'AUDIT_RECORD'
  | 'MIXED'
  | 'NOT_APPLICABLE';

export type RequirementLevel =
  | 'REQUIRED'
  | 'NOT_REQUIRED'
  | 'OPTIONAL'
  | 'CONTEXTUAL'
  | 'NOT_APPLICABLE'
  | 'UNKNOWN';

export type PublicationApplicability =
  | 'APPLICABLE'
  | 'NOT_APPLICABLE'
  | 'INDIRECT'
  | 'UNKNOWN';

export type CurrentImplementationSupport =
  | 'IMPLEMENTED'
  | 'PARTIALLY_IMPLEMENTED'
  | 'NOT_IMPLEMENTED'
  | 'UNKNOWN';

export type GovernanceSeverity =
  | 'CRITICAL'
  | 'HIGH'
  | 'MODERATE'
  | 'LOW'
  | 'INFORMATIONAL';

export type VerificationConfidence = 'CONFIRMED' | 'INFERRED' | 'UNKNOWN';

export type WeosArtifactCatalogueEntry = Readonly<{
  canonicalType: WeosArtifactType;
  canonicalPurpose: string;
  diagnosisScoped: boolean;
  versioned: boolean;
  currentRevisionModels: readonly string[];
  candidateGovernedClassification: CandidateGovernedClassification;
  reviewRequirement: RequirementLevel;
  approvalRequirement: RequirementLevel;
  decisionRequirement: RequirementLevel;
  publicationApplicability: PublicationApplicability;
  currentPrismaModels: readonly string[];
  currentImplementationModel: string | null;
  currentImplementationSupport: CurrentImplementationSupport;
  currentAlignmentClassification: WeosAlignmentClassification;
  severity: GovernanceSeverity;
  verificationConfidence: VerificationConfidence;
  canonicalDocuments: readonly string[];
  knownDivergences: readonly string[];
}>;

const A = WEOS_ALIGNMENT_CLASSIFICATIONS;
const CANON_FOUNDATION = 'WEOS-CANON-001';
const CANON_DIAGNOSIS = 'WEOS-CANON-002';
const CANON_CASE = 'WEOS-CANON-003';
const CANON_EDUCATION = 'WEOS-CANON-004';
const CANON_KNOWLEDGE = 'WEOS-CANON-005';
const CANON_AI = 'WEOS-CANON-006';
const CANON_GOVERNANCE = 'WEOS-CANON-007';
const CANON_PUBLICATION = 'WEOS-ARCH-004';
const CANON_AUTHORITY = 'WEOS-ARCH-008';

function entry(input: WeosArtifactCatalogueEntry): WeosArtifactCatalogueEntry {
  return input;
}

export const WEOS_CANONICAL_ARTIFACT_CATALOGUE = {
  [WEOS_ARTIFACT_TYPES.DIAGNOSIS_REGISTRY]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.DIAGNOSIS_REGISTRY,
    canonicalPurpose: 'Stable diagnosis identity and canonical naming anchor.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNED_KNOWLEDGE',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['DiagnosisRegistry'],
    currentImplementationModel: 'DiagnosisRegistry',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_FOUNDATION, CANON_DIAGNOSIS],
    knownDivergences: [
      'Operational permission changes lack first-class governance provenance.',
      'Deprecation lacks replacement and historical context fields.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.DIAGNOSIS_ALIAS]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.DIAGNOSIS_ALIAS,
    canonicalPurpose:
      'Governed synonym, abbreviation, or search term for diagnosis identity resolution.',
    diagnosisScoped: true,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNED_KNOWLEDGE',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['DiagnosisAlias'],
    currentImplementationModel: 'DiagnosisAlias',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_DIAGNOSIS],
    knownDivergences: [
      'Alias source exists but review provenance, rationale, collision adjudication, and deactivation history are not first-class.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.DIAGNOSIS_REGISTRY_CANDIDATE]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.DIAGNOSIS_REGISTRY_CANDIDATE,
    canonicalPurpose:
      'Candidate diagnosis identity used for duplicate-safe registry growth.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'CANDIDATE_KNOWLEDGE',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'NOT_APPLICABLE',
    currentPrismaModels: ['DiagnosisRegistryCandidate'],
    currentImplementationModel: 'DiagnosisRegistryCandidate',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_DIAGNOSIS, CANON_GOVERNANCE],
    knownDivergences: [
      'Candidate review/create/merge state exists, but approval and creation are not represented as generic governance records.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.REGISTRY_ACTIVATION_STATE]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.REGISTRY_ACTIVATION_STATE,
    canonicalPurpose:
      'Registry lifecycle/activation state, distinct from editorial completeness.',
    diagnosisScoped: true,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'OPERATIONAL_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [
      'DiagnosisRegistry.status',
      'DiagnosisRegistry.active',
    ],
    currentImplementationModel: 'DiagnosisRegistry',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_DIAGNOSIS],
    knownDivergences: [
      'Activation review fields exist, but lifecycle transitions do not consistently carry governance decision records.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.DIAGNOSIS_OPERATIONAL_PERMISSION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.DIAGNOSIS_OPERATIONAL_PERMISSION,
    canonicalPurpose:
      'Stored permission for learner-answer eligibility or automated generation participation.',
    diagnosisScoped: true,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'OPERATIONAL_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [
      'DiagnosisRegistry.isPlayable',
      'DiagnosisRegistry.isGeneratable',
    ],
    currentImplementationModel: 'DiagnosisRegistry',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_DIAGNOSIS, CANON_PUBLICATION],
    knownDivergences: [
      'Permission grant/withdrawal lacks first-class actor, authority, reason, expiry, and review obligation.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.DIAGNOSIS_ONBOARDING_PROGRESS]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.DIAGNOSIS_ONBOARDING_PROGRESS,
    canonicalPurpose:
      'Workflow progress state for diagnosis portfolio completion.',
    diagnosisScoped: true,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'OPERATIONAL_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['DiagnosisRegistry.onboardingStatus'],
    currentImplementationModel: 'DiagnosisRegistry',
    currentImplementationSupport: 'IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_DIAGNOSIS],
    knownDivergences: [
      'Values such as READY_FOR_REVIEW or COMPLETE can become stale or be interpreted as broad readiness.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.DIAGNOSIS_OPERATION_READINESS]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.DIAGNOSIS_OPERATION_READINESS,
    canonicalPurpose:
      'Computed readiness for metadata review, scaffold generation, case generation, coordinated review, or publication assessment.',
    diagnosisScoped: true,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['DiagnosisEditorialOnboardingService'],
    currentImplementationModel: 'DiagnosisEditorialOnboardingService',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_DIAGNOSIS, CANON_GOVERNANCE],
    knownDivergences: [
      'Readiness is projected from service logic rather than a versioned, operation-specific, explainable readiness contract.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.EDITORIAL_BRIEF]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.EDITORIAL_BRIEF,
    canonicalPurpose:
      'Editor-governed diagnosis intent used to guide education, graph work, and case generation.',
    diagnosisScoped: true,
    versioned: true,
    currentRevisionModels: ['DiagnosisEditorialBrief.version'],
    candidateGovernedClassification: 'GOVERNED_KNOWLEDGE',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['DiagnosisEditorialBrief'],
    currentImplementationModel: 'DiagnosisEditorialBrief',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_DIAGNOSIS, CANON_GOVERNANCE],
    knownDivergences: [
      'Brief status is a string and version is stored on the mutable brief record.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.LEARNING_GOAL]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.LEARNING_GOAL,
    canonicalPurpose:
      'Governed learning outcome, currently represented as structured brief content.',
    diagnosisScoped: true,
    versioned: true,
    currentRevisionModels: ['DiagnosisEditorialBrief.version'],
    candidateGovernedClassification: 'GOVERNED_KNOWLEDGE',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['DiagnosisEditorialBrief.learningGoals'],
    currentImplementationModel: 'DiagnosisEditorialBrief',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_DIAGNOSIS, CANON_CASE],
    knownDivergences: [
      'Stable identifiers, material-change detection, deprecation/replacement semantics, and exact review traceability are incomplete.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.TEACHING_RULE]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.TEACHING_RULE,
    canonicalPurpose:
      'Reusable governed teaching constraint or guidance for a diagnosis.',
    diagnosisScoped: true,
    versioned: true,
    currentRevisionModels: ['DiagnosisTeachingRule.version'],
    candidateGovernedClassification: 'MIXED',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['DiagnosisTeachingRule'],
    currentImplementationModel: 'DiagnosisTeachingRule',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_DIAGNOSIS, CANON_KNOWLEDGE],
    knownDivergences: [
      'Status and source are strings; no separate revision table.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.REASONING_PATH]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.REASONING_PATH,
    canonicalPurpose:
      'Governed diagnostic reasoning pattern used for generation and education.',
    diagnosisScoped: true,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'MIXED',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['ReasoningPath'],
    currentImplementationModel: 'ReasoningPath',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_KNOWLEDGE],
    knownDivergences: [
      'Readiness score is stored on the artifact and approval is implicit in status.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.REASONING_VALIDATION_RESULT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.REASONING_VALIDATION_RESULT,
    canonicalPurpose:
      'Structured reasoning draft validation result for trust, unsupported-claim, coverage, evidence, and hallucination-risk signals.',
    diagnosisScoped: true,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['ReasoningDraftValidationRun'],
    currentImplementationModel: 'ReasoningDraftValidationRun',
    currentImplementationSupport: 'IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'LOW',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_KNOWLEDGE, CANON_GOVERNANCE],
    knownDivergences: [
      'Passing validation is not approval and must remain so.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.CLINICAL_CASE]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.CLINICAL_CASE,
    canonicalPurpose:
      'Educational expression of a diagnosis presented as a playable clinical case.',
    diagnosisScoped: true,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'MIXED',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: ['Case', 'CaseRevision'],
    currentImplementationModel: 'Case',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.DIVERGENT,
    severity: 'CRITICAL',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE, CANON_GOVERNANCE],
    knownDivergences: [
      'The Case aggregate remains an independently mutable source used by governance, publication, scheduling, or learner-facing paths instead of functioning only as a controlled projection of an exact current revision.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.CASE_REVISION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.CASE_REVISION,
    canonicalPurpose: 'Immutable revision snapshot of clinical case material.',
    diagnosisScoped: true,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'GOVERNED_KNOWLEDGE',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: ['CaseRevision'],
    currentImplementationModel: 'CaseRevision',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE],
    knownDivergences: [
      'Current revision linkage and dependent records remain nullable.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.CASE_EXPLANATION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.CASE_EXPLANATION,
    canonicalPurpose:
      'Case-specific reasoning and learning explanation, distinct from diagnosis education.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision', 'ExplanationContent.version'],
    candidateGovernedClassification: 'MIXED',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: ['Case.explanation', 'ExplanationContent'],
    currentImplementationModel: 'Case',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE, CANON_EDUCATION],
    knownDivergences: [
      'Explanation exists both on mutable Case JSON and ExplanationContent without first-class governed revision decisions.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.CLINICAL_CLUE]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.CLINICAL_CLUE,
    canonicalPurpose:
      'Ordered clue content that drives gameplay and diagnostic reasoning.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'MIXED',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: ['Case.clues', 'CaseRevision.clues'],
    currentImplementationModel: 'Case',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.DIVERGENT,
    severity: 'CRITICAL',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE],
    knownDivergences: [
      'JSON storage is not itself the issue; clue identity depends on array position/order, so annotations, progression analyses, application provenance, and learner exposure can become stale without revision-aware clue keys.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.CLUE_PROGRESSION_ANALYSIS]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.CLUE_PROGRESSION_ANALYSIS,
    canonicalPurpose:
      'Assessment of clue progression, lock-in risk, ambiguity, and discriminator emergence.',
    diagnosisScoped: true,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['CaseClueProgressionAnalysis'],
    currentImplementationModel: 'CaseClueProgressionAnalysis',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE],
    knownDivergences: ['Model links to Case, not exact CaseRevision.'],
  }),
  [WEOS_ARTIFACT_TYPES.CLUE_DISCRIMINATOR_ANNOTATION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.CLUE_DISCRIMINATOR_ANNOTATION,
    canonicalPurpose:
      'Editor annotation describing how a clue discriminates against mimics.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['CaseClueDiscriminatorAnnotation'],
    currentImplementationModel: 'CaseClueDiscriminatorAnnotation',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE],
    knownDivergences: [
      'Annotation links to Case and clue order, not exact clue revision identity.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.ESCALATION_ANNOTATION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.ESCALATION_ANNOTATION,
    canonicalPurpose:
      'Assessment of whether a case covers a required escalation concept.',
    diagnosisScoped: true,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['CaseEscalationAnnotation'],
    currentImplementationModel: 'CaseEscalationAnnotation',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'LOW',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE],
    knownDivergences: ['Annotation links to Case, not exact CaseRevision.'],
  }),
  [WEOS_ARTIFACT_TYPES.DIAGNOSIS_EDUCATION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.DIAGNOSIS_EDUCATION,
    canonicalPurpose:
      'Diagnosis-level educational artifact independent of one case narrative.',
    diagnosisScoped: true,
    versioned: true,
    currentRevisionModels: ['DiagnosisEducationRevision'],
    candidateGovernedClassification: 'MIXED',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: ['DiagnosisEducation', 'DiagnosisEducationRevision'],
    currentImplementationModel: 'DiagnosisEducation',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.DIVERGENT,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_EDUCATION, CANON_GOVERNANCE],
    knownDivergences: [
      'Status combines generation, review, approval, publication, rejection, and archival states.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.DIAGNOSIS_EDUCATION_REVISION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.DIAGNOSIS_EDUCATION_REVISION,
    canonicalPurpose: 'Immutable snapshot of diagnosis education content.',
    diagnosisScoped: true,
    versioned: true,
    currentRevisionModels: ['DiagnosisEducationRevision'],
    candidateGovernedClassification: 'GOVERNED_KNOWLEDGE',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: ['DiagnosisEducationRevision'],
    currentImplementationModel: 'DiagnosisEducationRevision',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_EDUCATION],
    knownDivergences: [
      'No separate version-specific approval or publication decision record.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.GRAPH_CANDIDATE]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.GRAPH_CANDIDATE,
    canonicalPurpose:
      'Candidate extracted knowledge awaiting review, approval, rejection, merge, or promotion.',
    diagnosisScoped: true,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'CANDIDATE_KNOWLEDGE',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['DiagnosisGraphCandidate'],
    currentImplementationModel: 'DiagnosisGraphCandidate',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_KNOWLEDGE],
    knownDivergences: [
      'Candidate/fact architecture is present, but promotion decision provenance is domain-specific.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.GRAPH_FACT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.GRAPH_FACT,
    canonicalPurpose: 'Governed diagnosis knowledge fact.',
    diagnosisScoped: true,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNED_KNOWLEDGE',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['DiagnosisGraphFact'],
    currentImplementationModel: 'DiagnosisGraphFact',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_KNOWLEDGE],
    knownDivergences: [
      'Activation/provenance is not a generic governance record.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.TEACHING_RELATIONSHIP]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.TEACHING_RELATIONSHIP,
    canonicalPurpose: 'Governed relationship between diagnoses for teaching.',
    diagnosisScoped: true,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'MIXED',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['DiagnosisTeachingRelationship'],
    currentImplementationModel: 'DiagnosisTeachingRelationship',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_KNOWLEDGE],
    knownDivergences: [
      'No universal Governance Record captures activation/rejection, authority context, exact rationale, domain-specific lifecycle, versioning, or supersession for teaching relationships.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.EVIDENCE_NODE]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.EVIDENCE_NODE,
    canonicalPurpose:
      'Clinical finding or evidence concept, not an external source.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'MIXED',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['EvidenceNode'],
    currentImplementationModel: 'EvidenceNode',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_KNOWLEDGE],
    knownDivergences: [
      'Source authority and decision provenance are not first-class.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.EVIDENCE_RELATIONSHIP]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.EVIDENCE_RELATIONSHIP,
    canonicalPurpose:
      'Relationship between a diagnosis and a clinical evidence concept.',
    diagnosisScoped: true,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'MIXED',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['DiagnosisEvidenceRelationship'],
    currentImplementationModel: 'DiagnosisEvidenceRelationship',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_KNOWLEDGE],
    knownDivergences: [
      'Relationship status is not backed by generic decision record.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.EVIDENCE_SOURCE]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.EVIDENCE_SOURCE,
    canonicalPurpose:
      'External scientific, guideline, or institutional source identity.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNED_KNOWLEDGE',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_KNOWLEDGE, CANON_GOVERNANCE],
    knownDivergences: [
      'JSON references do not establish governed source identity.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.CLAIM_SUPPORT_LINK]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.CLAIM_SUPPORT_LINK,
    canonicalPurpose: 'Link between a content claim and supporting source.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNED_KNOWLEDGE',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_KNOWLEDGE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for claim-to-source support.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.REFERENCE_LIST]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.REFERENCE_LIST,
    canonicalPurpose: 'Citation presentation attached to content.',
    diagnosisScoped: true,
    versioned: true,
    currentRevisionModels: ['DiagnosisEducationRevision'],
    candidateGovernedClassification: 'MIXED',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['DiagnosisEducation.references'],
    currentImplementationModel: 'DiagnosisEducation',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_EDUCATION],
    knownDivergences: [
      'References are JSON text/payload, not governed evidence sources.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.EVIDENCE_ASSESSMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.EVIDENCE_ASSESSMENT,
    canonicalPurpose:
      'Assessment of source quality, applicability, recency, conflict, or retraction.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_KNOWLEDGE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for evidence assessment.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.DIFFERENTIAL_MAPPING]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.DIFFERENTIAL_MAPPING,
    canonicalPurpose:
      'Resolution record connecting raw differential text to registry entries.',
    diagnosisScoped: true,
    versioned: true,
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [
      'CaseDifferentialMapping',
      'EducationDifferentialMapping',
    ],
    currentImplementationModel: 'CaseDifferentialMapping',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE, CANON_EDUCATION],
    knownDivergences: ['Revision IDs are nullable.'],
  }),
  [WEOS_ARTIFACT_TYPES.DIFFERENTIAL_LINK]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.DIFFERENTIAL_LINK,
    canonicalPurpose: 'Resolved differential relationship attached to content.',
    diagnosisScoped: true,
    versioned: true,
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
    candidateGovernedClassification: 'GOVERNED_KNOWLEDGE',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['CaseDifferentialLink', 'EducationDifferentialLink'],
    currentImplementationModel: 'CaseDifferentialLink',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE, CANON_EDUCATION],
    knownDivergences: [
      'Revision IDs are nullable and lifecycle decisions are absent.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.AI_DRAFT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.AI_DRAFT,
    canonicalPurpose: 'AI-generated candidate change or artifact proposal.',
    diagnosisScoped: true,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'CANDIDATE_KNOWLEDGE',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'NOT_APPLICABLE',
    currentPrismaModels: ['AiDraftRevisionAudit'],
    currentImplementationModel: 'AiDraftRevisionAudit',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_AI],
    knownDivergences: [
      'Acceptance, controlled application, and approval are not universally separated.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.AI_DRAFT_ACCEPTANCE]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.AI_DRAFT_ACCEPTANCE,
    canonicalPurpose: 'Decision to accept an AI draft as candidate material.',
    diagnosisScoped: true,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'DECISION_RECORD',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'NOT_APPLICABLE',
    currentPrismaModels: ['AiDraftRevisionAudit.reviewStatus'],
    currentImplementationModel: 'AiDraftRevisionAudit',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_AI, CANON_GOVERNANCE],
    knownDivergences: [
      'Acceptance can be stored as status but is not a generic governance decision.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.CLUE_REVISION_DRAFT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.CLUE_REVISION_DRAFT,
    canonicalPurpose:
      'Candidate clue-level change awaiting review or application.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'CANDIDATE_KNOWLEDGE',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'NOT_APPLICABLE',
    currentPrismaModels: ['CaseClueRevisionDraft'],
    currentImplementationModel: 'CaseClueRevisionDraft',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_AI, CANON_CASE],
    knownDivergences: [
      'Status is string; decision/application fields share the draft row.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.VALIDATION_RESULT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.VALIDATION_RESULT,
    canonicalPurpose:
      'Structured result from validation rules applied to an artifact or revision.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['CaseValidationRun'],
    currentImplementationModel: 'CaseValidationRun',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE, CANON_GOVERNANCE],
    knownDivergences: [
      'Revision ID is nullable; validation outcome can drive lifecycle status transitions.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.EDITORIAL_ASSESSMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.EDITORIAL_ASSESSMENT,
    canonicalPurpose:
      'Structured clinical, educational, reasoning, evidence, safety, or publication-readiness assessment.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_GOVERNANCE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for unified structured editorial assessment.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.CLINICAL_ASSESSMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.CLINICAL_ASSESSMENT,
    canonicalPurpose:
      'Structured assessment of clinical correctness and clinical safety for an artifact or revision.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE, CANON_GOVERNANCE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for structured clinical assessment.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.EDUCATIONAL_ASSESSMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.EDUCATIONAL_ASSESSMENT,
    canonicalPurpose:
      'Structured assessment of educational value, learning objective fit, and learner-facing explanation quality.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_EDUCATION, CANON_GOVERNANCE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for structured educational assessment.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.REASONING_ASSESSMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.REASONING_ASSESSMENT,
    canonicalPurpose:
      'Structured assessment of diagnostic reasoning quality and path validity.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_KNOWLEDGE, CANON_GOVERNANCE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for structured reasoning assessment.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.SAFETY_ASSESSMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.SAFETY_ASSESSMENT,
    canonicalPurpose:
      'Structured assessment of learner, clinical, escalation, and unsafe-content risk.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE, CANON_GOVERNANCE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for structured safety assessment.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.LEARNING_GOAL_COVERAGE_ASSESSMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.LEARNING_GOAL_COVERAGE_ASSESSMENT,
    canonicalPurpose:
      'Assessment that a case covers a governed learning goal with stated strength and evidence.',
    diagnosisScoped: true,
    versioned: true,
    currentRevisionModels: ['CaseRevision', 'DiagnosisEditorialBrief.version'],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['CaseLearningGoalCoverage'],
    currentImplementationModel: 'CaseLearningGoalCoverage',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE],
    knownDivergences: [
      'Coverage references learningGoalId string and Case, not exact brief revision and case revision.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.EDITORIAL_REVIEW]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.EDITORIAL_REVIEW,
    canonicalPurpose: 'Review workflow identity, assignment, and progress.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['CaseReview'],
    currentImplementationModel: 'CaseReview',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_GOVERNANCE],
    knownDivergences: [
      'CaseReview.revisionId is nullable and embeds legacy decision fields.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.REVIEW_PACKET_SNAPSHOT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.REVIEW_PACKET_SNAPSHOT,
    canonicalPurpose:
      'Immutable decision-supporting review context with exact revision evidence and hashes.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['CaseReviewContextSnapshot'],
    currentImplementationModel: 'CaseReviewContextSnapshot',
    currentImplementationSupport: 'IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'LOW',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_GOVERNANCE],
    knownDivergences: [
      'Snapshot does not independently record judgement, authority, outcome, effect, or obligations.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.EDITORIAL_DECISION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.EDITORIAL_DECISION,
    canonicalPurpose:
      'Material editorial decision for an exact artifact revision with rationale and authority context.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'DECISION_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['CaseEditorialDecision', 'CaseReview.decision'],
    currentImplementationModel: 'CaseEditorialDecision',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_GOVERNANCE],
    knownDivergences: [
      'Case-specific only and overlaps mutable projections and legacy review decision.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.READINESS_ASSESSMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.READINESS_ASSESSMENT,
    canonicalPurpose:
      'Explainable computed readiness result for a specific operation.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [
      'DiagnosisEditorialOnboardingService',
      'CaseEligibilityPolicyService',
      'ReasoningPath.readinessScore',
    ],
    currentImplementationModel: 'DiagnosisEditorialOnboardingService',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.DIVERGENT,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_GOVERNANCE],
    knownDivergences: [
      'Readiness is distributed across service logic, statuses, and stored scores.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.PUBLICATION_READINESS_ASSESSMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.PUBLICATION_READINESS_ASSESSMENT,
    canonicalPurpose:
      'Structured readiness assessment for publication prerequisites, distinct from publication assessment and publication decision.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION, CANON_GOVERNANCE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for revision-specific publication readiness assessment.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.PUBLICATION_ASSESSMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.PUBLICATION_ASSESSMENT,
    canonicalPurpose:
      'Structured assessment that a specific approved revision satisfies publication requirements, distinct from readiness, publication decision, schedule, release, and learner exposure.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION, CANON_GOVERNANCE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for structured revision-specific publication assessment.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.PUBLICATION_DECISION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.PUBLICATION_DECISION,
    canonicalPurpose:
      'Decision to publish an exact approved artifact revision.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
    candidateGovernedClassification: 'DECISION_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [
      'Case.editorialStatus',
      'Case.publishedAt',
      'DiagnosisEducation.publishedAt',
    ],
    currentImplementationModel: 'Case',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.DIVERGENT,
    severity: 'CRITICAL',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION, CANON_GOVERNANCE],
    knownDivergences: [
      'Publication is represented as mutable status/timestamp projections.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.PUBLISHED_ARTIFACT_VERSION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.PUBLISHED_ARTIFACT_VERSION,
    canonicalPurpose: 'Immutable version selected for publication.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
    candidateGovernedClassification: 'GOVERNED_KNOWLEDGE',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'CRITICAL',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION],
    knownDivergences: [
      'No immutable published revision reference was identified.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.PUBLICATION_SCHEDULE]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.PUBLICATION_SCHEDULE,
    canonicalPurpose:
      'Operational schedule for when a published artifact is made available.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'OPERATIONAL_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: ['DailyCase'],
    currentImplementationModel: 'DailyCase',
    currentImplementationSupport: 'IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION],
    knownDivergences: [
      'Schedule points to mutable Case rather than published artifact version.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.RELEASE_EVENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.RELEASE_EVENT,
    canonicalPurpose: 'Event that makes scheduled content available.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'AUDIT_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for release event.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.LEARNER_EXPOSURE_REFERENCE]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.LEARNER_EXPOSURE_REFERENCE,
    canonicalPurpose:
      'Reference used by learner-facing reads to retrieve immutable published content.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'OPERATIONAL_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: ['DailyCase.caseId'],
    currentImplementationModel: 'DailyCase',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.DIVERGENT,
    severity: 'CRITICAL',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION, CANON_CASE],
    knownDivergences: [
      'Learner reads resolve through mutable Case rather than frozen published revision.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.WITHDRAWAL_RECORD]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.WITHDRAWAL_RECORD,
    canonicalPurpose:
      'Governed record withdrawing a published artifact version.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
    candidateGovernedClassification: 'DECISION_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for withdrawal record.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.SUPERSESSION_RECORD]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.SUPERSESSION_RECORD,
    canonicalPurpose:
      'Governed record replacing one artifact version with another.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
    candidateGovernedClassification: 'DECISION_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for supersession record.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.PUBLICATION_HISTORY]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.PUBLICATION_HISTORY,
    canonicalPurpose:
      'Chronological publication lifecycle history for an artifact version.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
    candidateGovernedClassification: 'AUDIT_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: ['CaseReviewEvent'],
    currentImplementationModel: 'CaseReviewEvent',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'INFERRED',
    canonicalDocuments: [CANON_PUBLICATION],
    knownDivergences: [
      'Publication history is not consistently first-class across artifacts.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.CONTROLLED_APPLICATION_RECORD]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.CONTROLLED_APPLICATION_RECORD,
    canonicalPurpose:
      'Record that an accepted candidate change was intentionally applied to a target artifact revision.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'NOT_APPLICABLE',
    currentPrismaModels: ['CaseClueRevisionDraft.appliedAt'],
    currentImplementationModel: 'CaseClueRevisionDraft',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_AI, CANON_GOVERNANCE],
    knownDivergences: [
      'Application fields are clue-specific and share the draft row.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.MATERIAL_CHANGE_DETERMINATION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.MATERIAL_CHANGE_DETERMINATION,
    canonicalPurpose:
      'Governed determination whether an edit invalidates validation, assessments, review, approval, publication, learner exposure, graph facts, teaching relationships, education coverage, or downstream dependencies.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [
      'case-review.service.ts',
      'diagnosis-editorial-workspace.service.ts',
      'CaseReviewContextSnapshot.invalidationReason',
    ],
    currentImplementationModel: null,
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_CASE, CANON_GOVERNANCE, CANON_PUBLICATION],
    knownDivergences: [
      'Some update paths reset approval or mark staleness, but no central auditable material-change determination contract exists.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.GOVERNANCE_RECORD]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.GOVERNANCE_RECORD,
    canonicalPurpose:
      'Record of why a material governance action occurred, under whose authority, for which artifact/revision, with what effect and obligations.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['CaseEditorialDecision'],
    currentImplementationModel: 'CaseEditorialDecision',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_GOVERNANCE],
    knownDivergences: [
      'Implemented primarily for case decisions and not all artifact families.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.AUDIT_EVENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.AUDIT_EVENT,
    canonicalPurpose:
      'Record that something happened, distinct from a governance decision.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'AUDIT_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [
      'CaseReviewEvent',
      'DiagnosisRegistryMergeLog',
      'service logs',
    ],
    currentImplementationModel: 'CaseReviewEvent',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_GOVERNANCE],
    knownDivergences: [
      'Audit events can be mistaken for governance records if not separated.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.AUTHORITY_ASSIGNMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.AUTHORITY_ASSIGNMENT,
    canonicalPurpose:
      'Explicit assignment of editorial authority to a person or role.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['User.role'],
    currentImplementationModel: 'User',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.DIVERGENT,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_AUTHORITY],
    knownDivergences: [
      'Global technical role substitutes for scoped editorial authority.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.AUTHORITY_SCOPE]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.AUTHORITY_SCOPE,
    canonicalPurpose:
      'Scope limiting authority by artifact, organization, specialty, or workflow.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_AUTHORITY],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for scoped authority.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.REVIEWER_ASSIGNMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.REVIEWER_ASSIGNMENT,
    canonicalPurpose: 'Assignment of reviewer to a review workflow.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: ['CaseRevision'],
    candidateGovernedClassification: 'OPERATIONAL_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: ['CaseReview.reviewerUserId'],
    currentImplementationModel: 'CaseReview',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.PARTIALLY_ALIGNED,
    severity: 'LOW',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_GOVERNANCE],
    knownDivergences: [
      'Assignment is case-specific and not scoped by authority model.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.CONFLICT_OF_INTEREST_DECLARATION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.CONFLICT_OF_INTEREST_DECLARATION,
    canonicalPurpose: 'Declaration of reviewer or decision-maker conflict.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_AUTHORITY],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for conflict-of-interest declaration.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.DISAGREEMENT_RECORD]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.DISAGREEMENT_RECORD,
    canonicalPurpose: 'Record of editorial disagreement requiring resolution.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_GOVERNANCE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for disagreement record.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.ADJUDICATION_RECORD]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.ADJUDICATION_RECORD,
    canonicalPurpose:
      'Resolution record for disagreement or contested decision.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_GOVERNANCE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for adjudication record.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.GOVERNANCE_EXCEPTION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.GOVERNANCE_EXCEPTION,
    canonicalPurpose: 'Approved exception to normal governance requirements.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_GOVERNANCE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for governance exception.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.EMERGENCY_CORRECTION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.EMERGENCY_CORRECTION,
    canonicalPurpose:
      'Emergency correction workflow for learner-facing or safety-sensitive content.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'CRITICAL',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION, CANON_GOVERNANCE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for emergency correction workflow.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.PUBLICATION_AUTHORITY]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.PUBLICATION_AUTHORITY,
    canonicalPurpose: 'Scoped authority to publish or withdraw artifacts.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: ['User.role'],
    currentImplementationModel: 'User',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: A.DIVERGENT,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_AUTHORITY, CANON_PUBLICATION],
    knownDivergences: [
      'Senior-editor/admin technical role is used as publication permission.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.ARTIFACT_OWNERSHIP]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.ARTIFACT_OWNERSHIP,
    canonicalPurpose: 'Ownership responsibility for an editorial artifact.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_AUTHORITY],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for artifact ownership.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.MAINTENANCE_OWNERSHIP]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.MAINTENANCE_OWNERSHIP,
    canonicalPurpose:
      'Responsibility for maintaining published content over time.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION, CANON_AUTHORITY],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for maintenance ownership.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.MAINTENANCE_ASSESSMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.MAINTENANCE_ASSESSMENT,
    canonicalPurpose:
      'Assessment that published content remains current and safe.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for maintenance assessment.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.EVIDENCE_REFRESH_TRIGGER]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.EVIDENCE_REFRESH_TRIGGER,
    canonicalPurpose:
      'Trigger indicating external evidence should be refreshed.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'OPERATIONAL_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_KNOWLEDGE, CANON_PUBLICATION],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for evidence refresh trigger.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.GUIDELINE_CHANGE_TRIGGER]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.GUIDELINE_CHANGE_TRIGGER,
    canonicalPurpose:
      'Trigger indicating guideline changes may affect content.',
    diagnosisScoped: false,
    versioned: false,
    currentRevisionModels: [],
    candidateGovernedClassification: 'OPERATIONAL_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_KNOWLEDGE, CANON_PUBLICATION],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for guideline-change trigger.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.REVIEW_DUE_DATE]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.REVIEW_DUE_DATE,
    canonicalPurpose: 'Date by which published content requires review.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'OPERATIONAL_RECORD',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for review-due date.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.REVALIDATION_OBLIGATION]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.REVALIDATION_OBLIGATION,
    canonicalPurpose:
      'Obligation to rerun validation or review after dependency/material change.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION, CANON_GOVERNANCE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for revalidation obligation.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.CORRECTION_WORKFLOW]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.CORRECTION_WORKFLOW,
    canonicalPurpose: 'Workflow for correcting governed or published content.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'GOVERNANCE_RECORD',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION, CANON_GOVERNANCE],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for correction workflow.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.RETIREMENT_ASSESSMENT]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.RETIREMENT_ASSESSMENT,
    canonicalPurpose: 'Assessment that content should be retired.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for retirement assessment.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.WITHDRAWAL_READINESS]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.WITHDRAWAL_READINESS,
    canonicalPurpose: 'Readiness assessment for withdrawing published content.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for withdrawal readiness.',
    ],
  }),
  [WEOS_ARTIFACT_TYPES.SUPERSESSION_REVIEW]: entry({
    canonicalType: WEOS_ARTIFACT_TYPES.SUPERSESSION_REVIEW,
    canonicalPurpose:
      'Review that determines whether a replacement supersedes current content.',
    diagnosisScoped: false,
    versioned: true,
    currentRevisionModels: [],
    candidateGovernedClassification: 'ASSESSMENT_RECORD',
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: A.MISSING,
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: [CANON_PUBLICATION],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for supersession review.',
    ],
  }),
} as const satisfies Record<WeosArtifactType, WeosArtifactCatalogueEntry>;

export const WEOS_CANONICAL_ARTIFACT_CATALOGUE_ENTRIES = Object.values(
  WEOS_CANONICAL_ARTIFACT_CATALOGUE,
);
