export const WEOS_ALIGNMENT_CLASSIFICATIONS = {
  ALIGNED: 'ALIGNED',
  PARTIALLY_ALIGNED: 'PARTIALLY_ALIGNED',
  DIVERGENT: 'DIVERGENT',
  MISSING: 'MISSING',
  LEGACY: 'LEGACY',
  UNKNOWN: 'UNKNOWN',
} as const;

export type WeosAlignmentClassification =
  (typeof WEOS_ALIGNMENT_CLASSIFICATIONS)[keyof typeof WEOS_ALIGNMENT_CLASSIFICATIONS];

export const WEOS_IMPLEMENTATION_SUPPORT = {
  IMPLEMENTED: 'IMPLEMENTED',
  PARTIALLY_IMPLEMENTED: 'PARTIALLY_IMPLEMENTED',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  UNKNOWN: 'UNKNOWN',
} as const;

export type WeosImplementationSupport =
  (typeof WEOS_IMPLEMENTATION_SUPPORT)[keyof typeof WEOS_IMPLEMENTATION_SUPPORT];

export const WEOS_GOVERNANCE_SEVERITIES = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MODERATE: 'MODERATE',
  LOW: 'LOW',
  INFORMATIONAL: 'INFORMATIONAL',
} as const;

export type WeosGovernanceSeverity =
  (typeof WEOS_GOVERNANCE_SEVERITIES)[keyof typeof WEOS_GOVERNANCE_SEVERITIES];

export const WEOS_VERIFICATION_CONFIDENCE = {
  CONFIRMED: 'CONFIRMED',
  INFERRED: 'INFERRED',
  UNKNOWN: 'UNKNOWN',
} as const;

export type WeosVerificationConfidence =
  (typeof WEOS_VERIFICATION_CONFIDENCE)[keyof typeof WEOS_VERIFICATION_CONFIDENCE];

export const WEOS_LIFECYCLE_STATE_CLASSES = {
  CANDIDATE: 'CANDIDATE',
  AUTHORING: 'AUTHORING',
  REVIEW: 'REVIEW',
  GOVERNED: 'GOVERNED',
  OPERATIONAL: 'OPERATIONAL',
  TERMINAL: 'TERMINAL',
  LEGACY: 'LEGACY',
} as const;

export type WeosLifecycleStateClass =
  (typeof WEOS_LIFECYCLE_STATE_CLASSES)[keyof typeof WEOS_LIFECYCLE_STATE_CLASSES];

export const WEOS_OPERATIONAL_PARTICIPATION_STATES = {
  PARTICIPATING: 'PARTICIPATING',
  NOT_PARTICIPATING: 'NOT_PARTICIPATING',
  SUSPENDED: 'SUSPENDED',
} as const;

export const WEOS_PLAYABILITY_PERMISSION_STATES = {
  GRANTED: 'GRANTED',
  REMOVED: 'REMOVED',
} as const;

export const WEOS_GENERATABILITY_PERMISSION_STATES = {
  GRANTED: 'GRANTED',
  REMOVED: 'REMOVED',
} as const;

export const WEOS_PUBLICATION_SCHEDULE_STATES = {
  PLANNED: 'PLANNED',
  SCHEDULED: 'SCHEDULED',
  CANCELLED: 'CANCELLED',
  RELEASED: 'RELEASED',
  EXPIRED: 'EXPIRED',
} as const;

export const WEOS_LEARNER_EXPOSURE_STATES = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  ENDED: 'ENDED',
  REVOKED: 'REVOKED',
} as const;

export const WEOS_READINESS_TYPES = {
  METADATA_REVIEW_READINESS: 'METADATA_REVIEW_READINESS',
  EDITORIAL_BRIEF_REVIEW_READINESS: 'EDITORIAL_BRIEF_REVIEW_READINESS',
  CASE_GENERATION_READINESS: 'CASE_GENERATION_READINESS',
  CASE_VALIDATION_READINESS: 'CASE_VALIDATION_READINESS',
  CASE_REVIEW_READINESS: 'CASE_REVIEW_READINESS',
  EDUCATION_REVIEW_READINESS: 'EDUCATION_REVIEW_READINESS',
  GRAPH_GOVERNANCE_READINESS: 'GRAPH_GOVERNANCE_READINESS',
  PLAYABILITY_READINESS: 'PLAYABILITY_READINESS',
  GENERATION_PERMISSION_READINESS: 'GENERATION_PERMISSION_READINESS',
  PUBLICATION_ASSESSMENT_READINESS: 'PUBLICATION_ASSESSMENT_READINESS',
  PUBLICATION_AUTHORISATION_READINESS: 'PUBLICATION_AUTHORISATION_READINESS',
  LEARNER_EXPOSURE_READINESS: 'LEARNER_EXPOSURE_READINESS',
  MAINTENANCE_REVALIDATION_READINESS: 'MAINTENANCE_REVALIDATION_READINESS',
} as const;

export type WeosReadinessType =
  (typeof WEOS_READINESS_TYPES)[keyof typeof WEOS_READINESS_TYPES];

export const WEOS_ASSESSMENT_TYPES = {
  CLINICAL_ASSESSMENT: 'CLINICAL_ASSESSMENT',
  EDUCATIONAL_ASSESSMENT: 'EDUCATIONAL_ASSESSMENT',
  REASONING_ASSESSMENT: 'REASONING_ASSESSMENT',
  EVIDENCE_ASSESSMENT: 'EVIDENCE_ASSESSMENT',
  SAFETY_ASSESSMENT: 'SAFETY_ASSESSMENT',
  PUBLICATION_READINESS_ASSESSMENT: 'PUBLICATION_READINESS_ASSESSMENT',
  LEARNING_GOAL_COVERAGE_ASSESSMENT: 'LEARNING_GOAL_COVERAGE_ASSESSMENT',
} as const;

export type WeosAssessmentType =
  (typeof WEOS_ASSESSMENT_TYPES)[keyof typeof WEOS_ASSESSMENT_TYPES];

export const WEOS_VALIDATION_OUTCOMES = {
  PASSED: 'PASSED',
  FAILED: 'FAILED',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
} as const;

export type WeosValidationOutcome =
  (typeof WEOS_VALIDATION_OUTCOMES)[keyof typeof WEOS_VALIDATION_OUTCOMES];

export const WEOS_DECISION_TYPES = {
  APPROVE_REVISION: 'APPROVE_REVISION',
  REJECT_REVISION: 'REJECT_REVISION',
  REQUIRE_REVISION: 'REQUIRE_REVISION',
  SUPERSEDE_REVISION: 'SUPERSEDE_REVISION',
  ACCEPT_AI_DRAFT: 'ACCEPT_AI_DRAFT',
  REJECT_AI_DRAFT: 'REJECT_AI_DRAFT',
  REQUEST_AI_DRAFT_CHANGES: 'REQUEST_AI_DRAFT_CHANGES',
  APPROVE_CANDIDATE_CREATION: 'APPROVE_CANDIDATE_CREATION',
  MERGE_CANDIDATE: 'MERGE_CANDIDATE',
  APPROVE_GRAPH_PROMOTION: 'APPROVE_GRAPH_PROMOTION',
  REJECT_GRAPH_CANDIDATE: 'REJECT_GRAPH_CANDIDATE',
  ACTIVATE_RELATIONSHIP: 'ACTIVATE_RELATIONSHIP',
  DEPRECATE_RELATIONSHIP: 'DEPRECATE_RELATIONSHIP',
  ACCEPT_CLUE_REVISION_DRAFT: 'ACCEPT_CLUE_REVISION_DRAFT',
  REJECT_CLUE_REVISION_DRAFT: 'REJECT_CLUE_REVISION_DRAFT',
  ACTIVATE_ARTIFACT: 'ACTIVATE_ARTIFACT',
  DEPRECATE_ARTIFACT: 'DEPRECATE_ARTIFACT',
  RETIRE_ARTIFACT: 'RETIRE_ARTIFACT',
  AUTHORISE_PUBLICATION: 'AUTHORISE_PUBLICATION',
  DECLINE_PUBLICATION: 'DECLINE_PUBLICATION',
  WITHDRAW_PUBLICATION: 'WITHDRAW_PUBLICATION',
  SUPERSEDE_PUBLICATION: 'SUPERSEDE_PUBLICATION',
  GRANT_GOVERNANCE_EXCEPTION: 'GRANT_GOVERNANCE_EXCEPTION',
  ADJUDICATE_DISAGREEMENT: 'ADJUDICATE_DISAGREEMENT',
} as const;

export type WeosDecisionType =
  (typeof WEOS_DECISION_TYPES)[keyof typeof WEOS_DECISION_TYPES];

export const WEOS_GOVERNANCE_RECORD_TYPES = {
  EDITORIAL_DECISION: 'EDITORIAL_DECISION',
  MATERIAL_CHANGE_DETERMINATION: 'MATERIAL_CHANGE_DETERMINATION',
  CONTROLLED_APPLICATION_RECORD: 'CONTROLLED_APPLICATION_RECORD',
  PUBLICATION_DECISION: 'PUBLICATION_DECISION',
  WITHDRAWAL_RECORD: 'WITHDRAWAL_RECORD',
  SUPERSESSION_RECORD: 'SUPERSESSION_RECORD',
  GOVERNANCE_EXCEPTION: 'GOVERNANCE_EXCEPTION',
  CONFLICT_OF_INTEREST_DECLARATION: 'CONFLICT_OF_INTEREST_DECLARATION',
  DISAGREEMENT_RECORD: 'DISAGREEMENT_RECORD',
  ADJUDICATION_RECORD: 'ADJUDICATION_RECORD',
  EMERGENCY_CORRECTION_RECORD: 'EMERGENCY_CORRECTION_RECORD',
} as const;

export const WEOS_GOVERNANCE_SOURCE_CONTEXT_TYPES = {
  REVIEW_PACKET_SNAPSHOT: 'REVIEW_PACKET_SNAPSHOT',
  ARTIFACT_CONTEXT_SNAPSHOT: 'ARTIFACT_CONTEXT_SNAPSHOT',
  VALIDATION_RESULT_REFERENCE: 'VALIDATION_RESULT_REFERENCE',
  ASSESSMENT_REFERENCE: 'ASSESSMENT_REFERENCE',
} as const;

export const WEOS_AUDIT_RECORD_TYPES = {
  REVIEW_EVENT: 'REVIEW_EVENT',
  AI_DRAFT_AUDIT: 'AI_DRAFT_AUDIT',
  REGISTRY_MERGE_EVENT: 'REGISTRY_MERGE_EVENT',
  STATUS_PROJECTION_EVENT: 'STATUS_PROJECTION_EVENT',
} as const;

export const WEOS_AUTHORITY_ARCHETYPES = {
  EDITORIAL_AUTHOR: 'EDITORIAL_AUTHOR',
  CLINICAL_REVIEWER: 'CLINICAL_REVIEWER',
  EDUCATIONAL_REVIEWER: 'EDUCATIONAL_REVIEWER',
  REASONING_REVIEWER: 'REASONING_REVIEWER',
  EVIDENCE_REVIEWER: 'EVIDENCE_REVIEWER',
  SAFETY_REVIEWER: 'SAFETY_REVIEWER',
  SENIOR_EDITOR: 'SENIOR_EDITOR',
  PUBLICATION_AUTHORITY: 'PUBLICATION_AUTHORITY',
  GOVERNANCE_ADJUDICATOR: 'GOVERNANCE_ADJUDICATOR',
} as const;

export const WEOS_TECHNICAL_ACTOR_TYPES = {
  ADMINISTRATOR: 'ADMINISTRATOR',
  SYSTEM_SERVICE: 'SYSTEM_SERVICE',
  AUTOMATION_WORKER: 'AUTOMATION_WORKER',
} as const;

export const WEOS_FINDING_SEVERITIES = {
  INFORMATIONAL: 'INFORMATIONAL',
  LOW: 'LOW',
  MODERATE: 'MODERATE',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;

export const WEOS_BLOCKING_EFFECTS = {
  NON_BLOCKING: 'NON_BLOCKING',
  BLOCKING: 'BLOCKING',
} as const;

export type WeosBlockingEffect =
  (typeof WEOS_BLOCKING_EFFECTS)[keyof typeof WEOS_BLOCKING_EFFECTS];
