export const WEOS_ALIGNMENT_CLASSIFICATIONS = {
  ALIGNED: 'ALIGNED',
  PARTIALLY_ALIGNED: 'PARTIALLY_ALIGNED',
  DIVERGENT: 'DIVERGENT',
  MISSING: 'MISSING',
  LEGACY: 'LEGACY',
  UNKNOWN: 'UNKNOWN',
} as const;

export type WeosAlignmentClassification =
  (typeof WEOS_ALIGNMENT_CLASSIFICATIONS)[keyof typeof WEOS_ALIGNMENT_CLASSIFICATIONS];

export const WEOS_IMPLEMENTATION_SUPPORT = {
  IMPLEMENTED: 'IMPLEMENTED',
  PARTIALLY_IMPLEMENTED: 'PARTIALLY_IMPLEMENTED',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  UNKNOWN: 'UNKNOWN',
} as const;

export type WeosImplementationSupport =
  (typeof WEOS_IMPLEMENTATION_SUPPORT)[keyof typeof WEOS_IMPLEMENTATION_SUPPORT];

export const WEOS_GOVERNANCE_SEVERITIES = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MODERATE: 'MODERATE',
  LOW: 'LOW',
  INFORMATIONAL: 'INFORMATIONAL',
} as const;

export type WeosGovernanceSeverity =
  (typeof WEOS_GOVERNANCE_SEVERITIES)[keyof typeof WEOS_GOVERNANCE_SEVERITIES];

export const WEOS_VERIFICATION_CONFIDENCE = {
  CONFIRMED: 'CONFIRMED',
  INFERRED: 'INFERRED',
  UNKNOWN: 'UNKNOWN',
} as const;

export type WeosVerificationConfidence =
  (typeof WEOS_VERIFICATION_CONFIDENCE)[keyof typeof WEOS_VERIFICATION_CONFIDENCE];

export const WEOS_EDITORIAL_LIFECYCLE_STATES = {
  DRAFT: 'DRAFT',
  GENERATED: 'GENERATED',
  CANDIDATE: 'CANDIDATE',
  VALIDATING: 'VALIDATING',
  VALIDATED: 'VALIDATED',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  IN_REVIEW: 'IN_REVIEW',
  NEEDS_CHANGES: 'NEEDS_CHANGES',
  APPROVED: 'APPROVED',
  READY_FOR_PUBLICATION: 'READY_FOR_PUBLICATION',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED',
  ARCHIVED: 'ARCHIVED',
  DEPRECATED: 'DEPRECATED',
  SUPERSEDED: 'SUPERSEDED',
  WITHDRAWN: 'WITHDRAWN',
} as const;

export type WeosEditorialLifecycleState =
  (typeof WEOS_EDITORIAL_LIFECYCLE_STATES)[keyof typeof WEOS_EDITORIAL_LIFECYCLE_STATES];

export const WEOS_OPERATIONAL_STATES = {
  ACTIVE: 'ACTIVE',
  HIDDEN: 'HIDDEN',
  DEPRECATED: 'DEPRECATED',
  DRAFT: 'DRAFT',
  PLAYABLE: 'PLAYABLE',
  NOT_PLAYABLE: 'NOT_PLAYABLE',
  GENERATABLE: 'GENERATABLE',
  NOT_GENERATABLE: 'NOT_GENERATABLE',
  SCHEDULED: 'SCHEDULED',
  AVAILABLE_TO_LEARNER: 'AVAILABLE_TO_LEARNER',
  UNAVAILABLE_TO_LEARNER: 'UNAVAILABLE_TO_LEARNER',
} as const;

export type WeosOperationalState =
  (typeof WEOS_OPERATIONAL_STATES)[keyof typeof WEOS_OPERATIONAL_STATES];

export const WEOS_READINESS_TYPES = {
  CASE_VALIDATION_READINESS: 'CASE_VALIDATION_READINESS',
  CASE_REVIEW_READINESS: 'CASE_REVIEW_READINESS',
  CASE_PUBLICATION_READINESS: 'CASE_PUBLICATION_READINESS',
  DIAGNOSIS_ONBOARDING_READINESS: 'DIAGNOSIS_ONBOARDING_READINESS',
  GENERATION_READINESS: 'GENERATION_READINESS',
  PLAYABILITY_READINESS: 'PLAYABILITY_READINESS',
  GRAPH_GOVERNANCE_READINESS: 'GRAPH_GOVERNANCE_READINESS',
  LEARNER_EXPOSURE_READINESS: 'LEARNER_EXPOSURE_READINESS',
} as const;

export type WeosReadinessType =
  (typeof WEOS_READINESS_TYPES)[keyof typeof WEOS_READINESS_TYPES];

export const WEOS_ASSESSMENT_TYPES = {
  VALIDATION_RESULT: 'VALIDATION_RESULT',
  CLINICAL_ASSESSMENT: 'CLINICAL_ASSESSMENT',
  EDUCATIONAL_ASSESSMENT: 'EDUCATIONAL_ASSESSMENT',
  REASONING_ASSESSMENT: 'REASONING_ASSESSMENT',
  EVIDENCE_ASSESSMENT: 'EVIDENCE_ASSESSMENT',
  SAFETY_ASSESSMENT: 'SAFETY_ASSESSMENT',
  REVIEW_ASSESSMENT: 'REVIEW_ASSESSMENT',
  QUALITY_SCORE: 'QUALITY_SCORE',
  READINESS_ASSESSMENT: 'READINESS_ASSESSMENT',
  PUBLICATION_READINESS_ASSESSMENT: 'PUBLICATION_READINESS_ASSESSMENT',
  COVERAGE_ASSESSMENT: 'COVERAGE_ASSESSMENT',
  AI_DRAFT_REVIEW: 'AI_DRAFT_REVIEW',
} as const;

export type WeosAssessmentType =
  (typeof WEOS_ASSESSMENT_TYPES)[keyof typeof WEOS_ASSESSMENT_TYPES];

export const WEOS_DECISION_TYPES = {
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  REQUEST_CHANGES: 'REQUEST_CHANGES',
  MARK_READY_TO_PUBLISH: 'MARK_READY_TO_PUBLISH',
  ACCEPT_DRAFT: 'ACCEPT_DRAFT',
  APPLY_CONTROLLED_CHANGE: 'APPLY_CONTROLLED_CHANGE',
  PUBLISH: 'PUBLISH',
  WITHDRAW: 'WITHDRAW',
  SUPERSEDE: 'SUPERSEDE',
} as const;

export type WeosDecisionType =
  (typeof WEOS_DECISION_TYPES)[keyof typeof WEOS_DECISION_TYPES];

export const WEOS_GOVERNANCE_RECORD_TYPES = {
  CONTEXT_SNAPSHOT: 'CONTEXT_SNAPSHOT',
  EDITORIAL_DECISION: 'EDITORIAL_DECISION',
  REVIEW_EVENT: 'REVIEW_EVENT',
  AI_DRAFT_AUDIT: 'AI_DRAFT_AUDIT',
  CONTROLLED_APPLICATION_RECORD: 'CONTROLLED_APPLICATION_RECORD',
  MATERIAL_CHANGE_DETERMINATION: 'MATERIAL_CHANGE_DETERMINATION',
  PUBLICATION_DECISION: 'PUBLICATION_DECISION',
  WITHDRAWAL_RECORD: 'WITHDRAWAL_RECORD',
  SUPERSESSION_RECORD: 'SUPERSESSION_RECORD',
} as const;

export type WeosGovernanceRecordType =
  (typeof WEOS_GOVERNANCE_RECORD_TYPES)[keyof typeof WEOS_GOVERNANCE_RECORD_TYPES];

export const WEOS_AUTHORITY_ROLES = {
  AUTHOR: 'AUTHOR',
  EDITOR: 'EDITOR',
  SENIOR_EDITOR: 'SENIOR_EDITOR',
  PUBLISHER: 'PUBLISHER',
  ADMINISTRATOR: 'ADMINISTRATOR',
  SYSTEM: 'SYSTEM',
} as const;

export type WeosAuthorityRole =
  (typeof WEOS_AUTHORITY_ROLES)[keyof typeof WEOS_AUTHORITY_ROLES];

export const WEOS_BLOCKER_SEVERITIES = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  BLOCKER: 'BLOCKER',
  CRITICAL: 'CRITICAL',
} as const;

export type WeosBlockerSeverity =
  (typeof WEOS_BLOCKER_SEVERITIES)[keyof typeof WEOS_BLOCKER_SEVERITIES];
