import type { WeosArtifactType } from './canonical-artifact-catalogue';

export const PHASE_1_PROTECTED_CATALOGUE_FIELDS = [
  'canonicalPurpose',
  'diagnosisScoped',
  'reviewRequirement',
  'approvalRequirement',
  'decisionRequirement',
  'publicationApplicability',
  'currentImplementationSupport',
  'currentAlignmentClassification',
  'severity',
  'verificationConfidence',
  'canonicalDocuments',
  'knownDivergences',
  'currentPrismaModels',
  'currentImplementationModel',
  'currentRevisionModels',
] as const;

export type Phase1ProtectedCatalogueField =
  (typeof PHASE_1_PROTECTED_CATALOGUE_FIELDS)[number];

export const PHASE_1_PROTECTED_ARTIFACT_CATALOGUE = {
  DIAGNOSIS_REGISTRY: {
    canonicalPurpose: 'Stable diagnosis identity and canonical naming anchor.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-001', 'WEOS-CANON-002'],
    knownDivergences: [
      'Operational permission changes lack first-class governance provenance.',
      'Deprecation lacks replacement and historical context fields.',
    ],
    currentPrismaModels: ['DiagnosisRegistry'],
    currentImplementationModel: 'DiagnosisRegistry',
    currentRevisionModels: [],
  },
  DIAGNOSIS_ALIAS: {
    canonicalPurpose:
      'Governed synonym, abbreviation, or search term for diagnosis identity resolution.',
    diagnosisScoped: true,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-002'],
    knownDivergences: [
      'Alias source exists but review provenance, rationale, collision adjudication, and deactivation history are not first-class.',
    ],
    currentPrismaModels: ['DiagnosisAlias'],
    currentImplementationModel: 'DiagnosisAlias',
    currentRevisionModels: [],
  },
  DIAGNOSIS_REGISTRY_CANDIDATE: {
    canonicalPurpose:
      'Candidate diagnosis identity used for duplicate-safe registry growth.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'NOT_APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-002', 'WEOS-CANON-007'],
    knownDivergences: [
      'Candidate review/create/merge state exists, but approval and creation are not represented as generic governance records.',
    ],
    currentPrismaModels: ['DiagnosisRegistryCandidate'],
    currentImplementationModel: 'DiagnosisRegistryCandidate',
    currentRevisionModels: [],
  },
  REGISTRY_ACTIVATION_STATE: {
    canonicalPurpose:
      'Registry lifecycle/activation state, distinct from editorial completeness.',
    diagnosisScoped: true,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-002'],
    knownDivergences: [
      'Activation review fields exist, but lifecycle transitions do not consistently carry governance decision records.',
    ],
    currentPrismaModels: [
      'DiagnosisRegistry.status',
      'DiagnosisRegistry.active',
    ],
    currentImplementationModel: 'DiagnosisRegistry',
    currentRevisionModels: [],
  },
  DIAGNOSIS_OPERATIONAL_PERMISSION: {
    canonicalPurpose:
      'Stored permission for learner-answer eligibility or automated generation participation.',
    diagnosisScoped: true,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-002', 'WEOS-ARCH-004'],
    knownDivergences: [
      'Permission grant/withdrawal lacks first-class actor, authority, reason, expiry, and review obligation.',
    ],
    currentPrismaModels: [
      'DiagnosisRegistry.isPlayable',
      'DiagnosisRegistry.isGeneratable',
    ],
    currentImplementationModel: 'DiagnosisRegistry',
    currentRevisionModels: [],
  },
  DIAGNOSIS_ONBOARDING_PROGRESS: {
    canonicalPurpose:
      'Workflow progress state for diagnosis portfolio completion.',
    diagnosisScoped: true,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-002'],
    knownDivergences: [
      'Values such as READY_FOR_REVIEW or COMPLETE can become stale or be interpreted as broad readiness.',
    ],
    currentPrismaModels: ['DiagnosisRegistry.onboardingStatus'],
    currentImplementationModel: 'DiagnosisRegistry',
    currentRevisionModels: [],
  },
  DIAGNOSIS_OPERATION_READINESS: {
    canonicalPurpose:
      'Computed readiness for metadata review, scaffold generation, case generation, coordinated review, or publication assessment.',
    diagnosisScoped: true,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-002', 'WEOS-CANON-007'],
    knownDivergences: [
      'Readiness is projected from service logic rather than a versioned, operation-specific, explainable readiness contract.',
    ],
    currentPrismaModels: ['DiagnosisEditorialOnboardingService'],
    currentImplementationModel: 'DiagnosisEditorialOnboardingService',
    currentRevisionModels: [],
  },
  EDITORIAL_BRIEF: {
    canonicalPurpose:
      'Editor-governed diagnosis intent used to guide education, graph work, and case generation.',
    diagnosisScoped: true,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-002', 'WEOS-CANON-007'],
    knownDivergences: [
      'Brief status is a string and version is stored on the mutable brief record.',
    ],
    currentPrismaModels: ['DiagnosisEditorialBrief'],
    currentImplementationModel: 'DiagnosisEditorialBrief',
    currentRevisionModels: ['DiagnosisEditorialBrief.version'],
  },
  LEARNING_GOAL: {
    canonicalPurpose:
      'Governed learning outcome, currently represented as structured brief content.',
    diagnosisScoped: true,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-002', 'WEOS-CANON-003'],
    knownDivergences: [
      'Stable identifiers, material-change detection, deprecation/replacement semantics, and exact review traceability are incomplete.',
    ],
    currentPrismaModels: ['DiagnosisEditorialBrief.learningGoals'],
    currentImplementationModel: 'DiagnosisEditorialBrief',
    currentRevisionModels: ['DiagnosisEditorialBrief.version'],
  },
  TEACHING_RULE: {
    canonicalPurpose:
      'Reusable governed teaching constraint or guidance for a diagnosis.',
    diagnosisScoped: true,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-002', 'WEOS-CANON-005'],
    knownDivergences: [
      'Status and source are strings; no separate revision table.',
    ],
    currentPrismaModels: ['DiagnosisTeachingRule'],
    currentImplementationModel: 'DiagnosisTeachingRule',
    currentRevisionModels: ['DiagnosisTeachingRule.version'],
  },
  REASONING_PATH: {
    canonicalPurpose:
      'Governed diagnostic reasoning pattern used for generation and education.',
    diagnosisScoped: true,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-005'],
    knownDivergences: [
      'Readiness score is stored on the artifact and approval is implicit in status.',
    ],
    currentPrismaModels: ['ReasoningPath'],
    currentImplementationModel: 'ReasoningPath',
    currentRevisionModels: [],
  },
  REASONING_VALIDATION_RESULT: {
    canonicalPurpose:
      'Structured reasoning draft validation result for trust, unsupported-claim, coverage, evidence, and hallucination-risk signals.',
    diagnosisScoped: true,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'LOW',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-005', 'WEOS-CANON-007'],
    knownDivergences: [
      'Passing validation is not approval and must remain so.',
    ],
    currentPrismaModels: ['ReasoningDraftValidationRun'],
    currentImplementationModel: 'ReasoningDraftValidationRun',
    currentRevisionModels: [],
  },
  CLINICAL_CASE: {
    canonicalPurpose:
      'Educational expression of a diagnosis presented as a playable clinical case.',
    diagnosisScoped: true,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'DIVERGENT',
    severity: 'CRITICAL',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003', 'WEOS-CANON-007'],
    knownDivergences: [
      'The Case aggregate remains an independently mutable source used by governance, publication, scheduling, or learner-facing paths instead of functioning only as a controlled projection of an exact current revision.',
    ],
    currentPrismaModels: ['Case', 'CaseRevision'],
    currentImplementationModel: 'Case',
    currentRevisionModels: ['CaseRevision'],
  },
  CASE_REVISION: {
    canonicalPurpose: 'Immutable revision snapshot of clinical case material.',
    diagnosisScoped: true,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003'],
    knownDivergences: [
      'Current revision linkage and dependent records remain nullable.',
    ],
    currentPrismaModels: ['CaseRevision'],
    currentImplementationModel: 'CaseRevision',
    currentRevisionModels: ['CaseRevision'],
  },
  CASE_EXPLANATION: {
    canonicalPurpose:
      'Case-specific reasoning and learning explanation, distinct from diagnosis education.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003', 'WEOS-CANON-004'],
    knownDivergences: [
      'Explanation exists both on mutable Case JSON and ExplanationContent without first-class governed revision decisions.',
    ],
    currentPrismaModels: ['Case.explanation', 'ExplanationContent'],
    currentImplementationModel: 'Case',
    currentRevisionModels: ['CaseRevision', 'ExplanationContent.version'],
  },
  CLINICAL_CLUE: {
    canonicalPurpose:
      'Ordered clue content that drives gameplay and diagnostic reasoning.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'DIVERGENT',
    severity: 'CRITICAL',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003'],
    knownDivergences: [
      'JSON storage is not itself the issue; clue identity depends on array position/order, so annotations, progression analyses, application provenance, and learner exposure can become stale without revision-aware clue keys.',
    ],
    currentPrismaModels: ['Case.clues', 'CaseRevision.clues'],
    currentImplementationModel: 'Case',
    currentRevisionModels: ['CaseRevision'],
  },
  CLUE_PROGRESSION_ANALYSIS: {
    canonicalPurpose:
      'Assessment of clue progression, lock-in risk, ambiguity, and discriminator emergence.',
    diagnosisScoped: true,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003'],
    knownDivergences: ['Model links to Case, not exact CaseRevision.'],
    currentPrismaModels: ['CaseClueProgressionAnalysis'],
    currentImplementationModel: 'CaseClueProgressionAnalysis',
    currentRevisionModels: ['CaseRevision'],
  },
  CLUE_DISCRIMINATOR_ANNOTATION: {
    canonicalPurpose:
      'Editor annotation describing how a clue discriminates against mimics.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003'],
    knownDivergences: [
      'Annotation links to Case and clue order, not exact clue revision identity.',
    ],
    currentPrismaModels: ['CaseClueDiscriminatorAnnotation'],
    currentImplementationModel: 'CaseClueDiscriminatorAnnotation',
    currentRevisionModels: ['CaseRevision'],
  },
  ESCALATION_ANNOTATION: {
    canonicalPurpose:
      'Assessment of whether a case covers a required escalation concept.',
    diagnosisScoped: true,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'LOW',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003'],
    knownDivergences: ['Annotation links to Case, not exact CaseRevision.'],
    currentPrismaModels: ['CaseEscalationAnnotation'],
    currentImplementationModel: 'CaseEscalationAnnotation',
    currentRevisionModels: ['CaseRevision'],
  },
  DIAGNOSIS_EDUCATION: {
    canonicalPurpose:
      'Diagnosis-level educational artifact independent of one case narrative.',
    diagnosisScoped: true,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'DIVERGENT',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-004', 'WEOS-CANON-007'],
    knownDivergences: [
      'Status combines generation, review, approval, publication, rejection, and archival states.',
    ],
    currentPrismaModels: ['DiagnosisEducation', 'DiagnosisEducationRevision'],
    currentImplementationModel: 'DiagnosisEducation',
    currentRevisionModels: ['DiagnosisEducationRevision'],
  },
  DIAGNOSIS_EDUCATION_REVISION: {
    canonicalPurpose: 'Immutable snapshot of diagnosis education content.',
    diagnosisScoped: true,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-004'],
    knownDivergences: [
      'No separate version-specific approval or publication decision record.',
    ],
    currentPrismaModels: ['DiagnosisEducationRevision'],
    currentImplementationModel: 'DiagnosisEducationRevision',
    currentRevisionModels: ['DiagnosisEducationRevision'],
  },
  GRAPH_CANDIDATE: {
    canonicalPurpose:
      'Candidate extracted knowledge awaiting review, approval, rejection, merge, or promotion.',
    diagnosisScoped: true,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-005'],
    knownDivergences: [
      'Candidate/fact architecture is present, but promotion decision provenance is domain-specific.',
    ],
    currentPrismaModels: ['DiagnosisGraphCandidate'],
    currentImplementationModel: 'DiagnosisGraphCandidate',
    currentRevisionModels: [],
  },
  GRAPH_FACT: {
    canonicalPurpose: 'Governed diagnosis knowledge fact.',
    diagnosisScoped: true,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-005'],
    knownDivergences: [
      'Activation/provenance is not a generic governance record.',
    ],
    currentPrismaModels: ['DiagnosisGraphFact'],
    currentImplementationModel: 'DiagnosisGraphFact',
    currentRevisionModels: [],
  },
  TEACHING_RELATIONSHIP: {
    canonicalPurpose: 'Governed relationship between diagnoses for teaching.',
    diagnosisScoped: true,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-005'],
    knownDivergences: [
      'No universal Governance Record captures activation/rejection, authority context, exact rationale, domain-specific lifecycle, versioning, or supersession for teaching relationships.',
    ],
    currentPrismaModels: ['DiagnosisTeachingRelationship'],
    currentImplementationModel: 'DiagnosisTeachingRelationship',
    currentRevisionModels: [],
  },
  EVIDENCE_NODE: {
    canonicalPurpose:
      'Clinical finding or evidence concept, not an external source.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-005'],
    knownDivergences: [
      'Source authority and decision provenance are not first-class.',
    ],
    currentPrismaModels: ['EvidenceNode'],
    currentImplementationModel: 'EvidenceNode',
    currentRevisionModels: [],
  },
  EVIDENCE_RELATIONSHIP: {
    canonicalPurpose:
      'Relationship between a diagnosis and a clinical evidence concept.',
    diagnosisScoped: true,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-005'],
    knownDivergences: [
      'Relationship status is not backed by generic decision record.',
    ],
    currentPrismaModels: ['DiagnosisEvidenceRelationship'],
    currentImplementationModel: 'DiagnosisEvidenceRelationship',
    currentRevisionModels: [],
  },
  EVIDENCE_SOURCE: {
    canonicalPurpose:
      'External scientific, guideline, or institutional source identity.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-005', 'WEOS-CANON-007'],
    knownDivergences: [
      'JSON references do not establish governed source identity.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  CLAIM_SUPPORT_LINK: {
    canonicalPurpose: 'Link between a content claim and supporting source.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-005'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for claim-to-source support.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  REFERENCE_LIST: {
    canonicalPurpose: 'Citation presentation attached to content.',
    diagnosisScoped: true,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-004'],
    knownDivergences: [
      'References are JSON text/payload, not governed evidence sources.',
    ],
    currentPrismaModels: ['DiagnosisEducation.references'],
    currentImplementationModel: 'DiagnosisEducation',
    currentRevisionModels: ['DiagnosisEducationRevision'],
  },
  EVIDENCE_ASSESSMENT: {
    canonicalPurpose:
      'Assessment of source quality, applicability, recency, conflict, or retraction.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-005'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for evidence assessment.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  DIFFERENTIAL_MAPPING: {
    canonicalPurpose:
      'Resolution record connecting raw differential text to registry entries.',
    diagnosisScoped: true,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003', 'WEOS-CANON-004'],
    knownDivergences: ['Revision IDs are nullable.'],
    currentPrismaModels: [
      'CaseDifferentialMapping',
      'EducationDifferentialMapping',
    ],
    currentImplementationModel: 'CaseDifferentialMapping',
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
  },
  DIFFERENTIAL_LINK: {
    canonicalPurpose: 'Resolved differential relationship attached to content.',
    diagnosisScoped: true,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003', 'WEOS-CANON-004'],
    knownDivergences: [
      'Revision IDs are nullable and lifecycle decisions are absent.',
    ],
    currentPrismaModels: ['CaseDifferentialLink', 'EducationDifferentialLink'],
    currentImplementationModel: 'CaseDifferentialLink',
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
  },
  AI_DRAFT: {
    canonicalPurpose: 'AI-generated candidate change or artifact proposal.',
    diagnosisScoped: true,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'NOT_APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-006'],
    knownDivergences: [
      'Acceptance, controlled application, and approval are not universally separated.',
    ],
    currentPrismaModels: ['AiDraftRevisionAudit'],
    currentImplementationModel: 'AiDraftRevisionAudit',
    currentRevisionModels: [],
  },
  AI_DRAFT_ACCEPTANCE: {
    canonicalPurpose: 'Decision to accept an AI draft as candidate material.',
    diagnosisScoped: true,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'NOT_APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-006', 'WEOS-CANON-007'],
    knownDivergences: [
      'Acceptance can be stored as status but is not a generic governance decision.',
    ],
    currentPrismaModels: ['AiDraftRevisionAudit.reviewStatus'],
    currentImplementationModel: 'AiDraftRevisionAudit',
    currentRevisionModels: [],
  },
  CLUE_REVISION_DRAFT: {
    canonicalPurpose:
      'Candidate clue-level change awaiting review or application.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'NOT_APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-006', 'WEOS-CANON-003'],
    knownDivergences: [
      'Status is string; decision/application fields share the draft row.',
    ],
    currentPrismaModels: ['CaseClueRevisionDraft'],
    currentImplementationModel: 'CaseClueRevisionDraft',
    currentRevisionModels: [],
  },
  VALIDATION_RESULT: {
    canonicalPurpose:
      'Structured result from validation rules applied to an artifact or revision.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003', 'WEOS-CANON-007'],
    knownDivergences: [
      'Revision ID is nullable; validation outcome can drive lifecycle status transitions.',
    ],
    currentPrismaModels: ['CaseValidationRun'],
    currentImplementationModel: 'CaseValidationRun',
    currentRevisionModels: ['CaseRevision'],
  },
  EDITORIAL_ASSESSMENT: {
    canonicalPurpose:
      'Structured clinical, educational, reasoning, evidence, safety, or publication-readiness assessment.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-007'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for unified structured editorial assessment.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  CLINICAL_ASSESSMENT: {
    canonicalPurpose:
      'Structured assessment of clinical correctness and clinical safety for an artifact or revision.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003', 'WEOS-CANON-007'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for structured clinical assessment.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  EDUCATIONAL_ASSESSMENT: {
    canonicalPurpose:
      'Structured assessment of educational value, learning objective fit, and learner-facing explanation quality.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-004', 'WEOS-CANON-007'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for structured educational assessment.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  REASONING_ASSESSMENT: {
    canonicalPurpose:
      'Structured assessment of diagnostic reasoning quality and path validity.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-005', 'WEOS-CANON-007'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for structured reasoning assessment.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  SAFETY_ASSESSMENT: {
    canonicalPurpose:
      'Structured assessment of learner, clinical, escalation, and unsafe-content risk.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003', 'WEOS-CANON-007'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for structured safety assessment.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  LEARNING_GOAL_COVERAGE_ASSESSMENT: {
    canonicalPurpose:
      'Assessment that a case covers a governed learning goal with stated strength and evidence.',
    diagnosisScoped: true,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003'],
    knownDivergences: [
      'Coverage references learningGoalId string and Case, not exact brief revision and case revision.',
    ],
    currentPrismaModels: ['CaseLearningGoalCoverage'],
    currentImplementationModel: 'CaseLearningGoalCoverage',
    currentRevisionModels: ['CaseRevision', 'DiagnosisEditorialBrief.version'],
  },
  EDITORIAL_REVIEW: {
    canonicalPurpose: 'Review workflow identity, assignment, and progress.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-007'],
    knownDivergences: [
      'CaseReview.revisionId is nullable and embeds legacy decision fields.',
    ],
    currentPrismaModels: ['CaseReview'],
    currentImplementationModel: 'CaseReview',
    currentRevisionModels: ['CaseRevision'],
  },
  REVIEW_PACKET_SNAPSHOT: {
    canonicalPurpose:
      'Immutable decision-supporting review context with exact revision evidence and hashes.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'LOW',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-007'],
    knownDivergences: [
      'Snapshot does not independently record judgement, authority, outcome, effect, or obligations.',
    ],
    currentPrismaModels: ['CaseReviewContextSnapshot'],
    currentImplementationModel: 'CaseReviewContextSnapshot',
    currentRevisionModels: ['CaseRevision'],
  },
  EDITORIAL_DECISION: {
    canonicalPurpose:
      'Material editorial decision for an exact artifact revision with rationale and authority context.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-007'],
    knownDivergences: [
      'Case-specific only and overlaps mutable projections and legacy review decision.',
    ],
    currentPrismaModels: ['CaseEditorialDecision', 'CaseReview.decision'],
    currentImplementationModel: 'CaseEditorialDecision',
    currentRevisionModels: ['CaseRevision'],
  },
  READINESS_ASSESSMENT: {
    canonicalPurpose:
      'Explainable computed readiness result for a specific operation.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'DIVERGENT',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-007'],
    knownDivergences: [
      'Readiness is distributed across service logic, statuses, and stored scores.',
    ],
    currentPrismaModels: [
      'DiagnosisEditorialOnboardingService',
      'CaseEligibilityPolicyService',
      'ReasoningPath.readinessScore',
    ],
    currentImplementationModel: 'DiagnosisEditorialOnboardingService',
    currentRevisionModels: ['CaseRevision'],
  },
  PUBLICATION_READINESS_ASSESSMENT: {
    canonicalPurpose:
      'Structured readiness assessment for publication prerequisites, distinct from publication assessment and publication decision.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004', 'WEOS-CANON-007'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for revision-specific publication readiness assessment.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  PUBLICATION_ASSESSMENT: {
    canonicalPurpose:
      'Structured assessment that a specific approved revision satisfies publication requirements, distinct from readiness, publication decision, schedule, release, and learner exposure.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004', 'WEOS-CANON-007'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for structured revision-specific publication assessment.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  PUBLICATION_DECISION: {
    canonicalPurpose:
      'Decision to publish an exact approved artifact revision.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'DIVERGENT',
    severity: 'CRITICAL',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004', 'WEOS-CANON-007'],
    knownDivergences: [
      'Publication is represented as mutable status/timestamp projections.',
    ],
    currentPrismaModels: [
      'Case.editorialStatus',
      'Case.publishedAt',
      'DiagnosisEducation.publishedAt',
    ],
    currentImplementationModel: 'Case',
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
  },
  PUBLISHED_ARTIFACT_VERSION: {
    canonicalPurpose: 'Immutable version selected for publication.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'CRITICAL',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004'],
    knownDivergences: [
      'No immutable published revision reference was identified.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
  },
  PUBLICATION_SCHEDULE: {
    canonicalPurpose:
      'Operational schedule for when a published artifact is made available.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004'],
    knownDivergences: [
      'Schedule points to mutable Case rather than published artifact version.',
    ],
    currentPrismaModels: ['DailyCase'],
    currentImplementationModel: 'DailyCase',
    currentRevisionModels: [],
  },
  RELEASE_EVENT: {
    canonicalPurpose: 'Event that makes scheduled content available.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for release event.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  LEARNER_EXPOSURE_REFERENCE: {
    canonicalPurpose:
      'Reference used by learner-facing reads to retrieve immutable published content.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'DIVERGENT',
    severity: 'CRITICAL',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004', 'WEOS-CANON-003'],
    knownDivergences: [
      'Learner reads resolve through mutable Case rather than frozen published revision.',
    ],
    currentPrismaModels: ['DailyCase.caseId'],
    currentImplementationModel: 'DailyCase',
    currentRevisionModels: ['CaseRevision'],
  },
  WITHDRAWAL_RECORD: {
    canonicalPurpose:
      'Governed record withdrawing a published artifact version.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for withdrawal record.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
  },
  SUPERSESSION_RECORD: {
    canonicalPurpose:
      'Governed record replacing one artifact version with another.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for supersession record.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
  },
  PUBLICATION_HISTORY: {
    canonicalPurpose:
      'Chronological publication lifecycle history for an artifact version.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'INFERRED',
    canonicalDocuments: ['WEOS-ARCH-004'],
    knownDivergences: [
      'Publication history is not consistently first-class across artifacts.',
    ],
    currentPrismaModels: ['CaseReviewEvent'],
    currentImplementationModel: 'CaseReviewEvent',
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
  },
  CONTROLLED_APPLICATION_RECORD: {
    canonicalPurpose:
      'Record that an accepted candidate change was intentionally applied to a target artifact revision.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'NOT_APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-006', 'WEOS-CANON-007'],
    knownDivergences: [
      'Application fields are clue-specific and share the draft row.',
    ],
    currentPrismaModels: ['CaseClueRevisionDraft.appliedAt'],
    currentImplementationModel: 'CaseClueRevisionDraft',
    currentRevisionModels: ['CaseRevision', 'DiagnosisEducationRevision'],
  },
  MATERIAL_CHANGE_DETERMINATION: {
    canonicalPurpose:
      'Governed determination whether an edit invalidates validation, assessments, review, approval, publication, learner exposure, graph facts, teaching relationships, education coverage, or downstream dependencies.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-003', 'WEOS-CANON-007', 'WEOS-ARCH-004'],
    knownDivergences: [
      'Some update paths reset approval or mark staleness, but no central auditable material-change determination contract exists.',
    ],
    currentPrismaModels: [
      'case-review.service.ts',
      'diagnosis-editorial-workspace.service.ts',
      'CaseReviewContextSnapshot.invalidationReason',
    ],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  GOVERNANCE_RECORD: {
    canonicalPurpose:
      'Record of why a material governance action occurred, under whose authority, for which artifact/revision, with what effect and obligations.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-007'],
    knownDivergences: [
      'Implemented primarily for case decisions and not all artifact families.',
    ],
    currentPrismaModels: ['CaseEditorialDecision'],
    currentImplementationModel: 'CaseEditorialDecision',
    currentRevisionModels: ['CaseRevision'],
  },
  AUDIT_EVENT: {
    canonicalPurpose:
      'Record that something happened, distinct from a governance decision.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-007'],
    knownDivergences: [
      'Audit events can be mistaken for governance records if not separated.',
    ],
    currentPrismaModels: [
      'CaseReviewEvent',
      'DiagnosisRegistryMergeLog',
      'service logs',
    ],
    currentImplementationModel: 'CaseReviewEvent',
    currentRevisionModels: [],
  },
  AUTHORITY_ASSIGNMENT: {
    canonicalPurpose:
      'Explicit assignment of editorial authority to a person or role.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'DIVERGENT',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-008'],
    knownDivergences: [
      'Global technical role substitutes for scoped editorial authority.',
    ],
    currentPrismaModels: ['User.role'],
    currentImplementationModel: 'User',
    currentRevisionModels: [],
  },
  AUTHORITY_SCOPE: {
    canonicalPurpose:
      'Scope limiting authority by artifact, organization, specialty, or workflow.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-008'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for scoped authority.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  REVIEWER_ASSIGNMENT: {
    canonicalPurpose: 'Assignment of reviewer to a review workflow.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'PARTIALLY_ALIGNED',
    severity: 'LOW',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-007'],
    knownDivergences: [
      'Assignment is case-specific and not scoped by authority model.',
    ],
    currentPrismaModels: ['CaseReview.reviewerUserId'],
    currentImplementationModel: 'CaseReview',
    currentRevisionModels: ['CaseRevision'],
  },
  CONFLICT_OF_INTEREST_DECLARATION: {
    canonicalPurpose: 'Declaration of reviewer or decision-maker conflict.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-008'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for conflict-of-interest declaration.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  DISAGREEMENT_RECORD: {
    canonicalPurpose: 'Record of editorial disagreement requiring resolution.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-007'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for disagreement record.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  ADJUDICATION_RECORD: {
    canonicalPurpose:
      'Resolution record for disagreement or contested decision.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-007'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for adjudication record.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  GOVERNANCE_EXCEPTION: {
    canonicalPurpose: 'Approved exception to normal governance requirements.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-007'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for governance exception.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  EMERGENCY_CORRECTION: {
    canonicalPurpose:
      'Emergency correction workflow for learner-facing or safety-sensitive content.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'CRITICAL',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004', 'WEOS-CANON-007'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for emergency correction workflow.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  PUBLICATION_AUTHORITY: {
    canonicalPurpose: 'Scoped authority to publish or withdraw artifacts.',
    diagnosisScoped: false,
    reviewRequirement: 'NOT_APPLICABLE',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'PARTIALLY_IMPLEMENTED',
    currentAlignmentClassification: 'DIVERGENT',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-008', 'WEOS-ARCH-004'],
    knownDivergences: [
      'Senior-editor/admin technical role is used as publication permission.',
    ],
    currentPrismaModels: ['User.role'],
    currentImplementationModel: 'User',
    currentRevisionModels: [],
  },
  ARTIFACT_OWNERSHIP: {
    canonicalPurpose: 'Ownership responsibility for an editorial artifact.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'MODERATE',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-008'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for artifact ownership.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  MAINTENANCE_OWNERSHIP: {
    canonicalPurpose:
      'Responsibility for maintaining published content over time.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004', 'WEOS-ARCH-008'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for maintenance ownership.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  MAINTENANCE_ASSESSMENT: {
    canonicalPurpose:
      'Assessment that published content remains current and safe.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for maintenance assessment.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  EVIDENCE_REFRESH_TRIGGER: {
    canonicalPurpose:
      'Trigger indicating external evidence should be refreshed.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-005', 'WEOS-ARCH-004'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for evidence refresh trigger.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  GUIDELINE_CHANGE_TRIGGER: {
    canonicalPurpose:
      'Trigger indicating guideline changes may affect content.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'INDIRECT',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-CANON-005', 'WEOS-ARCH-004'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for guideline-change trigger.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  REVIEW_DUE_DATE: {
    canonicalPurpose: 'Date by which published content requires review.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'NOT_APPLICABLE',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for review-due date.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  REVALIDATION_OBLIGATION: {
    canonicalPurpose:
      'Obligation to rerun validation or review after dependency/material change.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004', 'WEOS-CANON-007'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for revalidation obligation.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  CORRECTION_WORKFLOW: {
    canonicalPurpose: 'Workflow for correcting governed or published content.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'REQUIRED',
    decisionRequirement: 'REQUIRED',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004', 'WEOS-CANON-007'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for correction workflow.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  RETIREMENT_ASSESSMENT: {
    canonicalPurpose: 'Assessment that content should be retired.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for retirement assessment.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  WITHDRAWAL_READINESS: {
    canonicalPurpose: 'Readiness assessment for withdrawing published content.',
    diagnosisScoped: false,
    reviewRequirement: 'CONTEXTUAL',
    approvalRequirement: 'NOT_REQUIRED',
    decisionRequirement: 'NOT_APPLICABLE',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for withdrawal readiness.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
  SUPERSESSION_REVIEW: {
    canonicalPurpose:
      'Review that determines whether a replacement supersedes current content.',
    diagnosisScoped: false,
    reviewRequirement: 'REQUIRED',
    approvalRequirement: 'CONTEXTUAL',
    decisionRequirement: 'CONTEXTUAL',
    publicationApplicability: 'APPLICABLE',
    currentImplementationSupport: 'NOT_IMPLEMENTED',
    currentAlignmentClassification: 'MISSING',
    severity: 'HIGH',
    verificationConfidence: 'CONFIRMED',
    canonicalDocuments: ['WEOS-ARCH-004'],
    knownDivergences: [
      'No first-class model identified in the inspected repository paths at commit 944d04d for supersession review.',
    ],
    currentPrismaModels: [],
    currentImplementationModel: null,
    currentRevisionModels: [],
  },
} as const satisfies Record<
  WeosArtifactType,
  Record<Phase1ProtectedCatalogueField, unknown>
>;
